### ISSUE TITLE
Feature request: allow locations to be saved

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-butterflies-app#1]
A user who regularly records at the same location asks if we can enable locations to be saved, to avoid having to re-enter each time, or wait for GPS each time.

**Comment by DavidRoy** [comment]
We have discussed this requirement and would like to avoid saving of locations as it may lead to the use of site centroids.  We'd rather benefit from the use the GPS functionality.  The app will include auto-complete of previously-entered site locations. 

Closing this issue for now, but wider testing may raise new or similar issues
