### ISSUE TITLE
FAQ for how to get ID support

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#100]
Request from recorder:
_Having just entered a sighting of a butterfly which I couldn’t identify, I wonder whether there could be an ‘unidentified’ option on the app? If this was combined with a photograph, the species could be identified properly by someone more qualified. I had to put an option (dark green fritillary in this case) but that might well have been inaccurate._

**Comment by DavidRoy** [comment]
Not implement the request but add an FAQ to give advice on how to get an ID for butteflies - e.g. facebook, twitter, county recorder, iSpot, iNaturalist

**Comment by RichardFoxBC** [comment]
Suggested text for a new FAQ. What do you think @DavidRoy @AnthonyMcCluskey ? Please feel free to suggest edits/amendments.

**What if I am not sure which species it is?**
Identifying butterflies is not always straightforward and some very common and widespread species can be challenging to identify (e.g. Large, Small and Green-veined White).  Please don't submit sightings if you are not sure of the identification. 

The species pages in this app provide some guidance on identification (and we plan to add more in the future), including comparison photos for some species that are easily mistaken. You can also filter the species list (using the magnifying glass icon in the top right corner of the screen) by main colour, markings and/or size to help narrow down your options. If you are still not sure then post a photo on @savebutterflies social media accounts to get an identification. But remember, only submit a record if you are sure it is correct - if in doubt, leave it out.

**Comment by DavidRoy** [comment]
Excellent.  Looks ready to me
