### ISSUE TITLE
Stats have not updated for 2022

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#106]
Happy New Year everyone! 

Just spotted that the statistics report in my app has not refreshed properly for 2022. The year has changed but the reported number of records and species is still the same as for 2021. Please can you investigate and fix?

**Comment by kazlauskis** [comment]
Thanks, looks like after the website update the report stopped working. We'll work on it this as soon as we have some more capacity.

**Comment by DavidRoy** [comment]
@kazlauskis - Biren can look into this if you can confirm the report that needs to be reinstated

**Comment by kazlauskis** [comment]
There are two endpoints that don't work anymore:
`https://www.brc.ac.uk/irecord/api/v1/advanced_reports/recorded-taxa-list`
`https://www.brc.ac.uk/irecord/api/v1/advanced_reports/user-stats`

Yes, Biren might be able to help fix these.

**Comment by DavidRoy** [comment]
@BirenRathod can you investigate please

**Comment by BirenRathod** [comment]
@kazlauskis where can I find this report?

**Comment by BirenRathod** [comment]
@kazlauskis It is because you haven't used indicia_api v1 version which was used originally in old iRecord.

**Comment by kazlauskis** [comment]
You know it better, I didn't follow the indicia API development. Can you fix it?

**Comment by BirenRathod** [comment]
yes @kazlauskis I'm doing that. Just to check with you on new irecord.org.uk website there are two indicia_api & indicia_api_v2 modules. Which one we use for this?

**Comment by kazlauskis** [comment]
This issue is part of the old module which is stored in the `indicia_api` folder.

**Comment by BirenRathod** [comment]
@DavidRoy, @RichardFoxBC & @kazlauskis I have updated indicia_api module. Can somebody check if report is working fine or not? I can't check from my app.

**Comment by DavidRoy** [comment]
@BirenRathod the stats appear but I think they report the wrong year.  They show numbers for 2021, not 2022.  i.e. not the current year.  I'm not sure if the report is hard coded for year?

**Comment by BirenRathod** [comment]
@kazlauskis which report do you call from butterfly app?

**Comment by BirenRathod** [comment]
@DavidRoy The report uses the one created on Elasticsearch. So it should bring 2022 year data unless on Elasticsearch it filters only for 2021.

**Comment by kazlauskis** [comment]
@BirenRathod the `https://www.brc.ac.uk/irecord/api/v1/advanced_reports/user-stats` is still returning 404 for me in the app.

**Comment by DavidRoy** [comment]
@BirenRathod can you update me on progress with resolving this

**Comment by BirenRathod** [comment]
@DavidRoy There is a code for indicia_api which may be @johnvanvreda created while ago. that needs to update by @johnvanbreda. once done this should work fine. The code is already on irecord pantheon.

**Comment by DavidRoy** [comment]
@johnvanbreda - you created the reports to support Karolis working on the app.  Can you help resolve this issue?

**Comment by johnvanbreda** [comment]
I've now added code to the v1 branch with the reports that the D7 module supported. Although I've tested in isolation, it would be wise to test from the app before putting it live.

**Comment by DavidRoy** [comment]
Thanks @johnvanbreda.  Going straight to live is fine as very people will be recording butterflies at the moment.  Would make it easier for me to test

**Comment by BirenRathod** [comment]
@DavidRoy, @johnvanbreda & @kazlauskis That code has released on live now.

**Comment by RichardFoxBC** [comment]
Many thanks @johnvanbreda and @BirenRathod - stats are now reporting correctly for 2022 in my version of the app

**Comment by DavidRoy** [comment]
Me too. Thanks both!
