### ISSUE TITLE
Capture survey duration in single species count

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-butterflies-app#112]
The value should be mm:ss. It’s possible some timed counts could go over an hour.

**Comment by kazlauskis** [comment]
@RichardFoxBC do you have any preferences how we capture the duration value? 

At the moment, we're thinking of storing it using the mm:ss format but we’ll make the minutes part to not be restricted to 60 and so if the count runs say two hours then we can record it as e.g 120:00. Would that be OK?

**Comment by RichardFoxBC** [comment]
Yes that's fine

**Comment by DavidRoy** [comment]
@RichardFoxBC just to check that we should not put a maximum time limit on a timed search.  May an hour?  That still leaves the option of multiple searches in the same location on the same day?
