### ISSUE TITLE
Add stage to Single Species Timed Count mode

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#113]
Further discussion with my colleague Ian (who I've invited to see the demo at our next meeting) raised the need to include stage as part of this mode. Please include stage in the first step, along with site name and species selection. This can be defaulted to Adult, as it is in other modes.

**Comment by kazlauskis** [comment]
I understand you would like All to ask it every time when the survey starts, is that right? How often would ppl record non adults? We already allow to change the stage when you open the occurrence page in the survey, only that the user would have to change that multiple times if recording lots non-adults.

**Comment by RichardFoxBC** [comment]
Yes please. Timed counts of non-adult stages are common e.g. for larval webs of Marsh Fritillary or eggs of Brown Hairstreak.

**Comment by kazlauskis** [comment]
OK, adding this question changes the survey flow even more then, **species -> stage -> count (-> finish steps?)** 

I think, we might need to rethink how the current survey interface looks like. It would be good to know if Ian thinks we should be adding/moving any other attributes or reshuffling the survey more before we continue working on it 😄

**Comment by DavidRoy** [comment]
@RichardFoxBC do you think we should keep this survey flow simpler
 species -> count -> stage -> finish steps

Once the species is selected the stage can be changed by clicking on the name.  This works if we assume that the most typical use of the single-species survey is for adults

**Comment by DavidRoy** [comment]
Looks good to me. I'm generally in favour of having this option for more species as we can't necessarily anticipate the sorts of projects that will want to monitoring individual species

**Comment by RichardFoxBC** [comment]
@kazlauskis I've made a few changes to the species table to correct the species selection available for timed count mode. I presume these will just be updated automatically and won't need you to do anything. If you want to check in the app, Speckled Wood should not now be available, but Silver-washed Fritillary, Wall and Small Blue should be (but weren't before)

**Comment by kazlauskis** [comment]
OK, thanks! We'll have to pull it into the Beta app but that should be straightforward and will come out with the next update.
