### ISSUE TITLE
Should we make the links to iRecord accounts clearer?

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-butterflies-app#114]
We occasionally get emails from users of the butterfly app who are alarmed when they receive notifications from iRecord, and the latest example is from a user who is insistent that they don't have an iRecord account and that we should not be contacting them.

The "About" section of the iRecord Butterflies app does say that records are stored within "the iRecord website" but it does not explicitly say anything about accounts and notifications. Should we add something about this? If so I can draft some text.

**Comment by DavidRoy** [comment]
I found this hard to understand the when the app has 'iRecord' in the name, but yes, anything to make the about text better is very welcome

**Comment by kitenetter** [comment]
In the final main paragraph of the "About" page, after the sentence "Any records you submit ... and national butterfly databases", I would suggest adding this text:

Your registration with this app also creates an account on the iRecord website, and you may receive notification emails from iRecord informing you about any checks and feedback on your records. If you wish, you can log on to the iRecord website using the same email and password combination. On the website, you can view your records by choosing the "Explore" menu and then "My records", and you can control your notifications by editing your account settings.

Then have "Records may be collated ..." as a new paragraph.

[Note to self: app users are also informed about having an iRecord account when they receive their email to verify the account.]
