### ISSUE TITLE
Popup and FAQ text for Single Species Timed Count mode

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#115]
Here's is our suggested text for the popup:

Use this feature for timed counts of priority species. Select the species and life stage and provide a site name. Weather details should be added automatically or you can add them manually. During the survey, tap the Count each time you see the target species. The app will track the time and route.

Such surveys may contribute to UK Butterfly Monitoring Scheme trends.

**Comment by RichardFoxBC** [comment]
And here is text for a new FAQ:

**Will my single-species timed count contribute to the UK Butterfly Monitoring Scheme (UKBMS)?**

Timed counts form an important part of the UKBMS dataset, enabling more robust national and regional trends to be calculated for priority species when transect data are limited. Single species timed counts submitted via this app will be made available to the UKBMS and may contribute to the species trends. 

In order to contribute, counts should be carried out in accordance with UKBMS guidance notes (https://ukbms.org/guidance-recording-forms), conducted at the peak of the species’ flight period and carried out in suitable weather conditions. Data are much more useful to the UKBMS, and more likely to contribute, when the same species is monitored at the same site over many years.

The UKBMS has also published guidance for Marsh Fritillary larval web counts and Brown Hairstreak egg counts. These counts can also be entered via the app in the same way.

**Comment by DavidRoy** [comment]
That's great, thanks
