### ISSUE TITLE
Location name not submitted with records?

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#118]
I submitted a record today with a location name.  The record uploaded ok, but the location name is missing.  See: 
https://irecord.org.uk/record-details?occurrence_id=24298992

@Vilius-Stankaitis can you check that location name is included in the record submission

**Comment by Vilius-Stankaitis** [comment]
@DavidRoy  It is fixed now. Thank you for finding this issue
