### ISSUE TITLE
Add a lifecycle chart

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-butterflies-app#12]
> Suggestion is to use these: https://www.ukbutterflies.co.uk/species.php?species=tages

Missing lifecycle charts: 
- Danaus plexippus
- Issoria lathonia
- Lampides boeticus
- Nymphalis antiopa
- Nymphalis polychloros

**Comment by DavidRoy** [comment]
or - https://butterfly-conservation.org/butterflies/adonis-blue

**Comment by kazlauskis** [comment]
@RichardFoxBC there are few species charts missing, is it OK to release the app without these?

**Comment by RichardFoxBC** [comment]
Yes that's fine @kazlauskis Those are all rare migrant species so the life cycle chart isn't really relevant for the UK
