### ISSUE TITLE
Speckled Wood should not be in list of species for single-species count?

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#120]
@RichardFoxBC to confirm
@Vilius-Stankaitis to update spreadsheet?
![irb1](https://user-images.githubusercontent.com/2699478/157413719-39d0316b-0b0b-401c-b3fc-c4c60e09a32b.png)

**Comment by kazlauskis** [comment]
@DavidRoy can you update to a newer iOS Beta release (136)?

**Comment by DavidRoy** [comment]
Thanks.  All fine now
