### ISSUE TITLE
Disable 'back' button from main single-species-timed count page when survey starts?

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#121]
When a single-species timed count survey has started (e.g. after species has been selected), the back button should not be an option.
@RichardFoxBC do you agree?
![irb3](https://user-images.githubusercontent.com/2699478/157414257-978fbca2-7546-4d3f-abe9-dcbd8ab8688d.png)

**Comment by RichardFoxBC** [comment]
Yes I agree. Please remove the back button on this screen

**Comment by kazlauskis** [comment]
All the surveys have Back and Finish buttons at the moment. Do you want us to remove it from all of them to keep it consistent? 

I think, we should allow the user to leave the survey to check some species ID in the guide or read the FAQ.

**Comment by RichardFoxBC** [comment]
OK that's a good reason @kazlauskis , but the problem is that having click Back from a timed count, it is not obvious how you get back to the timed count that you are in the middle of

**Comment by kazlauskis** [comment]
What about adding a popup when the user taps Back? It could explain how to continue the survey. Also, maybe pause the timer.

**Comment by RichardFoxBC** [comment]
Yes good ideas @kazlauskis - pressing Back should pause the Timed Count timer - would it also stop tracking the area searched? Pop-up could read "To resume your timed count, select My Records at the bottom of the screen and then tap on the relevant count"

**Comment by kazlauskis** [comment]
Thanks. Yes, we can stop the area tracking too. I would like to wait to see how much other work there is to finalise the Beta first before committing to this but we can definitely add the popup with the text now.

**Comment by RichardFoxBC** [comment]
@kazlauskis This popup doesn't seem to be in the new beta. Is it going to be implemented before the release?

**Comment by kazlauskis** [comment]
We haven't added the popup yet. We'll add the text but won't stop the GPS or the timer for now. We could do those in the next update though - please create separate tickets.
