### ISSUE TITLE
Record dates not showing on map

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#122]
Hi, when I look at the new map none of my records have the date. All of them show "Invalid date" when I tap on them to see the details.

**Comment by Vilius-Stankaitis** [comment]
Hi, @RichardFoxBC  I have fixed this. Thank you, for finding this issue.

**Comment by RichardFoxBC** [comment]
Thanks @Vilius-Stankaitis So should I see the correct dates in the beta now or only when a new verison of the app is released?

**Comment by Vilius-Stankaitis** [comment]
In the new app version :). Should be later today

**Comment by RichardFoxBC** [comment]
This is working now for me in the new Beta. @DavidRoy could you just check that you can see dates for all your previous records in the My Records map view please? If so, we can close this issue

**Comment by DavidRoy** [comment]
All good, thanks
