### ISSUE TITLE
Autofill of weather data

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#124]
A couple of potential issues with the autofill of weather data in the single species timed count option:

1. Where does this data come from? I've just tried two dummy counts, one on my home Wifi and one on 4G connection in the same location. Both filled weather data that seemed incorrect e.g. 11% sunshine when in reality there is 100% sunshine and wind direction NW when the Met Officer weather app says that the current wind direction for my location is SSW.

2. The temperature doesn't seem to autofill at all. Is it meant to?

**Comment by Vilius-Stankaitis** [comment]
@RichardFoxBC https://openweathermap.org/find

**Comment by kazlauskis** [comment]
Thanks. Since this app doesn't require global weather info (like the ButterflyCount app does where this comes from), I suggest to explore some more UK-focussed weather APIs out there at some point.

**Comment by RichardFoxBC** [comment]
Just to confirm that the app is now prefilling the temperature data for me. I'll close this issue but create a new one (for the future about exploring a UK weather API
