### ISSUE TITLE
Record verification status in area part of single species timed count

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#125]
I've verified some dummy single species timed count records that I entered yesterday. The app correctly notified me that they had been verified and the verification icons in My Records all worked beautifully. However, if I open the submitted timed count and click on Area to show the route walked and the locations of the records logged, these are all shown as orange dots rather than with the verification status that has now been applied. I just want to check that that is what you would expect i.e the verification status is not shown on that view?

**Comment by kazlauskis** [comment]
Currently, this view doesn't reflect the verification statuses, only shows the walked trail and where the occurrences have been recorded for a given survey. I agree it would be good to change the colour these map markers too. We'll see how much work there is to do that.
