### ISSUE TITLE
Double check on Finish for timed count

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#127]
Just starting to receive comments back from testers. First one:

"If you hit Finish the count by mistake and want to carry on, you cant. So you have to start again and either lose that data or submit two partial counts for the same place. I know you can pause the timing (though that is not obvious for a beginner). Maybe we would all soon learn not to do it but it might be handy to be able to continue a count from the same count from your pending box (but maybe that could be misused?)"

I don't think that we should allow people to restart timed counts from the Pending in My Records (and it might not be technically feasible anyway) but we could consider including an additional pop-up when people press Finish, which checks that they do want to finish the count. Could this be done please?

**Comment by kazlauskis** [comment]
@RichardFoxBC sure, what would you like the Finish popup to say?

**Comment by RichardFoxBC** [comment]
@kazlauskis "Are you sure you want to finish this timed count?" Then give options for "Yes, finish count" and "No, continue count"
Does that sound ok?
