### ISSUE TITLE
Timed Count with zero sightings

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#129]
Is it possible to submit a timed count with no sightings? I feel that it should be and the app submitted one for me but it has not come up in iRecord @DavidRoy

**Comment by kazlauskis** [comment]
Submitting an occurrence with the 0 count sets a `zero_abundance=true` to it. I think, this shows up as a crossed-out entry in the verifiers list but not sure if comes up in other reports.

**Comment by RichardFoxBC** [comment]
This record has now come through in iRecord with all of the correct details.

**Comment by kazlauskis** [comment]
@DavidRoy at the moment, we don't set any abundance value for either `zero_abundance` or actual occurrences. In the app we count the number of subsamples to report on the total species number in the list. We nevertheless can add a default abundance=1 for normal occurrences and abundance=0 for `zero_abundance` ones if it helps?

**Comment by DavidRoy** [comment]
ok, that makes sense.  Let's leave for the time being until we can discuss options and the iRecord report/download requirements.  I'll close this for now to reduce clutter
