### ISSUE TITLE
Defining polygon for timed count

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#131]
Another comment from a tester:

"When wanting to draw an area rather than let GPS plot your route, its not obvious that you cant use that function without turning off the GPS slider. So I wonder if its worth adding after 'Please draw area on map (turn off GPS)'"

My first thought is that we need some more info for users that it is even possible to do this. This could be via a FAQ, but I do wonder if we need something more up front too? I've not tested this functionality to see what happens if you predefine a polygon and then record within it - indeed I'm not even sure what you are supposed to do? Do you leave the GPS slider off and, if so, does the count just allocate all of your sightings to the polygon rather than capturing unique GPS fixes for each one?

**Comment by kazlauskis** [comment]
The trail editing functionality can be fiddly and ideally users wouldn't need to use it and rely on the GPS instead. So I've got mixed feelings about advocating the manual drawing functionality to every user. I agree, it would be good to add something to the FAQ though. If you draw a line and then turn on the GPS tracking then it will continue adding a trail from the last point on the map that you have drawn. If you've drawn an area (polygon) the app will continue adding points to the polygon. Polygons don't play nice with walked trails though. That is unless the user is walking around the field that it surveys.

The GPS can be turned on/off independently from the actual occurrence counting, that is each occurrence would still acquire a precise location even if the area tracking GPS is off.
