### ISSUE TITLE
Confusion species timed counts

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#134]
Are we happy to go ahead without the planned addition of extra categories for confusion species? We had discussed the need for this previously. Basically, as I understand it (@DavidRoy correct me if I'm wrong), if someone selects Pearl-bordered Fritillary from the single species timed count selection, the count page should show three species entries, each of which can be counted: Pearl-bordered Fritillary, Small Pearl-bordered Fritillary and 'unidentified PBF/Small PBF'. Similarly, if the user selects High Brown Fritillary then the count page should show this species plus Dark Green Fritillary and 'unidentified HBF/DGF'. It should not happen the other way around i.e. if a user selects either Small Pearl-bordered Fritillary or Dark Green Fritillary then it is just a normal timed count of the selected species.

**Comment by DavidRoy** [comment]
@RichardFoxBC yes, this would be the next priority
@kazlauskis can you advise when you could fit in this next requirement and do you have enough detail

**Comment by kazlauskis** [comment]
This is for two species, is that right?

- **Pearl-bordered Fritillary** = [Pearl-bordered Fritillary, Small Pearl-bordered Fritillary and 'unidentified PBF/Small PBF']
- **High Brown Fritillary** = [High Brown Fritillary, Dark Green Fritillary and 'unidentified HBF/DGF']

Which warehouse IDs 'unidentified' options map to?

**Comment by DavidRoy** [comment]
@kazlauskis remind me of the taxon list ID we use for the app.  I'll add the aggregate taxa needed for PBF/Small PBF and HBF/DGF

**Comment by kazlauskis** [comment]
You've set the species ids to the UKSI list (id=15).

**Comment by DavidRoy** [comment]
@kazlauskis here are the new aggregate taxa
PBF/Small PBF = 544542
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/544542

HBF/DGF = 544546
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/544546
