### ISSUE TITLE
Back button from Single-species timed count

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#139]
Hi, I've just noticed that when you look at an **uploaded** single species timed count e.g. to see the verification status of each sightings within it, when you tap "Back" to go back to the main My records page, it comes up with the "Leaving survey" popup warning re resuming the count. I don't think it should do that when the count has already been uploaded.

**Comment by Vilius-Stankaitis** [comment]
@RichardFoxBC Hello, I will hide the popup when the survey is uploaded. Thank you for finding this.
