### ISSUE TITLE
Add sample ID to ElasticSearch occurrences output

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-butterflies-app#140]
Currently, fetching `services/rest/es-occurrences/_search` doesn't include the occurrence's parent sample ID in the output. For us to be able to link the occurrences we need a parent sample ID included.

Links to #138

**Comment by kazlauskis** [comment]
@johnvanbreda to advice if this is doable.

**Comment by kazlauskis** [comment]
I have found `event.event_id` might be linked to sample ID, but not sure if this is that.

**Comment by johnvanbreda** [comment]
Correct - event.event_id is the sample ID, and event.parent_event_id is the parent sample ID. See https://github.com/Indicia-Team/support_files/blob/master/Elasticsearch/docs/occurrences-document-structure.md for the full list.

**Comment by kazlauskis** [comment]
Great, thanks for the documentation! Closing this now.
