### ISSUE TITLE
Stats not reporting correctly

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#143]
Hi all, I've been using the app quite a bit over the last couple of weeks and it is working well. It is really nice to see the notifications of record verification coming in. However, I noticed that the Records (2022) and Species recorded (2022) statistics are not reporting correctly for me. They seem to be stuck and are not advancing despite having made more records and seen new species.

**Comment by RichardFoxBC** [comment]
It may be related to the above but I've also not received any of the pop-up Thank You messages that are meant to appear after the submission of certain numbers of records each calendar year.

**Comment by kazlauskis** [comment]
Yes, there is an issue with the website report. 

The user stats report emits [this error](
https://irecord.org.uk/admin/reports/dblog/event/53768). I can reproduce this by logging into the iRecord Butterflies app and going to the user stats page. It strangely works for some accounts.
```
Warning: Division by zero in RecorderMetrics->getUserMetrics() (line 210 of /code/web/modules/custom/indicia_advanced_reports/src/RecorderMetrics.php)
```

@johnvanbreda would you be able to take a look at it?

**Comment by RichardFoxBC** [comment]
@kazlauskis @johnvanbreda  confirmed the stats are now reporting correctly in the app for me. Many thanks. 

@kazlauskis do you think the lack of pop-up thank you messages is related? My app now tells me that I've submitted 51 records in 2022 but I haven't had any pop-up thank you messages.

**Comment by kazlauskis** [comment]
Thanks John. 

@RichardFoxBC yes, the "Thank You" alert depends on this report so it should be working fine now. Please reopen the issue if this still doesn't appear to you.
