### ISSUE TITLE
app running slow in Android

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#144]
Hi, not sure there is much you'll be able to do with this info, but feedback from a user:

"The App is very to slow to load & also a lot slower within the map location it hangs for quite a while."

**Comment by kazlauskis** [comment]
What is user's device, Android and the app version?

**Comment by RichardFoxBC** [comment]
I'll ask

**Comment by RichardFoxBC** [comment]
Hi @kazlauskis  The user has a LG K7 phone. Android version screen shot attached. They are using the most up-to-date version of our app v2:3.1 (171)
![Android version](https://user-images.githubusercontent.com/36193573/165112571-ab7f5162-726d-4262-b221-7b77f8c29319.png)

**Comment by kazlauskis** [comment]
Thanks, according to the [device spec](https://www.lg.com/us/cell-phones/lg-K330-Silver-k7) it has only 1.5Gb or RAM. The app requires a minimum of 3Gb (ideally 4Gb) to function properly. It was a low-end device even in the 2016 when it was originally release  and now it is simply too slow even if it runs the latest Android.
