### ISSUE TITLE
Image cropping functionality for photos

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#149]
Image classification works better with a cropped image of the target butterfly.  Implement image cropping functionality, analagous to Esurveyor

**Comment by RichardFoxBC** [comment]
I thought we agreed that photo cropping needed to implemented for the next release (i.e. version 5). I can't see any sign of it in the app. Without it the image recognition function doesn't work very well

**Comment by kazlauskis** [comment]
To do it properly will take a bit of time. We can do it next week but it is something that would require a bit more testing across different Android devices, essentially pushing the public release +2 weeks. Do you want us to do it now or can this wait?

**Comment by DavidRoy** [comment]
My view is push to live asap, initially without the cropping facility.  Then work on the new functionality straight after.  In the interim, could you add some text to the photo/camera roll screen to say that the image classifier will be more accurate with a cropped image?
@RichardFoxBC are you ok with this approach?

**Comment by RichardFoxBC** [comment]
Yes I can live with that, as long as we get on with incorporating cropping functionality soon after. The app already has text that says the species should be central and in focus, so I think that's OK
