### ISSUE TITLE
Finalise onboarding text and images

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#15]
Text and images for introductory pages when app first used

**Comment by kazlauskis** [comment]
This would typically be 1-5 slides. The text should be short, 1-2 sentences. Here are some examples:

<img width="370" alt="Screenshot 2021-02-25 at 08 54 40" src="https://user-images.githubusercontent.com/7383162/109128226-3295e600-7747-11eb-9038-4042b82e4f5e.png">
<img width="363" alt="Screenshot 2021-02-25 at 08 54 35" src="https://user-images.githubusercontent.com/7383162/109128246-3590d680-7747-11eb-926c-e577c3ab182c.png">
<img width="399" alt="Screenshot 2021-02-25 at 08 54 04" src="https://user-images.githubusercontent.com/7383162/109128250-36296d00-7747-11eb-989d-51f134678f29.png">
<img width="411" alt="Screenshot 2021-02-25 at 08 53 57" src="https://user-images.githubusercontent.com/7383162/109128255-375a9a00-7747-11eb-90c6-a1099ca40493.png">

**Comment by RichardFoxBC** [comment]
OK, I've no experience of writing these onboarding screens and have forgotten all the useful things we've previously said should appear on them, but here goes. 

First screen:

iRecord Butterflies slogan near the top of the screen, image of Peacock, text; Identify butterflies that you see
![Peacock (Neil Hulme)](https://user-images.githubusercontent.com/36193573/113314748-87a7b780-9304-11eb-9b0f-7c2fb4c12f12.jpg)

**Comment by RichardFoxBC** [comment]
Onboarding screen 2:

iRecord Butterflies slogan in same place as on screen 1, image Brimstone (whichever of the two attached possibilities works best with the screen size and text placing, text: Submit your sightings
![Brimstone-_5D32658](https://user-images.githubusercontent.com/36193573/113315162-e8cf8b00-9304-11eb-950a-4efd79f6881d.jpg)
![Brimstone-_5D32718](https://user-images.githubusercontent.com/36193573/113315180-ed943f00-9304-11eb-8fab-a25d92bd9ef2.jpg)

**Comment by RichardFoxBC** [comment]
Screen 3:

iRecord Butterflies slogan in same place as on screens 1 & 2, image Marsh Fritillary, text: Help protect butterflies and the environment
![Marsh Fritillary (Iain Leach)2](https://user-images.githubusercontent.com/36193573/113317032-dfdfb900-9306-11eb-9c50-17579570c035.jpg)

**Comment by RichardFoxBC** [comment]
No additional photographer credits needed - they are all listed already

**Comment by RichardFoxBC** [comment]
Do we need an onboarding screen that explains about the short tap / long tap option on the Record button? Or is there already a pop-up message that covers that?

**Comment by RichardFoxBC** [comment]
Do you think we need an onboarding screen to explain the need to create an iRecord account?

**Comment by kazlauskis** [comment]
Thanks, I think, the long/short tap popup covers that. For more ideas, you could also add to these texts something about: probability data, lots of search filters, multiple surveys, works offline, rich species guide, expert verification... kind of, how amazing our app is! 😄

**Comment by RichardFoxBC** [comment]
I'm not sure if we want all that sort of stuff in the onboarding screens. That's the sort of stuff that should appear in the app store alongside the app isn't it? Once they've got as far as installing the app, do we need to sell it to them?

**Comment by RichardFoxBC** [comment]
I do like the idea of highlighting the probability filters though. So could we have a new screen 2 that uses a screen shot of with the "What's flying in your area" banner and some colourful species below. Text below this could read: To help with identification, species are shown according to what is most likely to be seen in your area at this time of year.

**Comment by kazlauskis** [comment]
I agree, no need to sell it but useful to bring out the features that could be otherwise missed. I like your idea of the probability screen. Here is another example of screens used in Collins Bird guide app which has very similar filter searching functionality to ours.

![IMG_1105](https://user-images.githubusercontent.com/7383162/113327356-c47aab00-9312-11eb-98b9-d7e4758742fe.PNG)
![IMG_1104](https://user-images.githubusercontent.com/7383162/113327361-c5abd800-9312-11eb-917c-b157b468f7d6.PNG)
![IMG_1103](https://user-images.githubusercontent.com/7383162/113327367-c6446e80-9312-11eb-8566-be907d471832.PNG)



![IMG_1106](https://user-images.githubusercontent.com/7383162/113327345-c17fba80-9312-11eb-910e-83a887428753.PNG)

**Comment by kazlauskis** [comment]
@RichardFoxBC I've added the onboarding screens. These could use background photos with more padding around the butterflies though. Are you OK with the following?

<img width="339" alt="Screenshot 2021-05-06 at 10 46 22" src="https://user-images.githubusercontent.com/7383162/117278275-882df380-ae58-11eb-97d7-c2c31b2956d5.png">
<img width="343" alt="Screenshot 2021-05-06 at 10 46 27" src="https://user-images.githubusercontent.com/7383162/117278296-8b28e400-ae58-11eb-8f8c-a9e28b7966ce.png">
<img width="337" alt="Screenshot 2021-05-06 at 10 46 13" src="https://user-images.githubusercontent.com/7383162/117278304-8d8b3e00-ae58-11eb-8fbf-b93ee235b2bf.png">
<img width="338" alt="Screenshot 2021-05-06 at 10 46 06" src="https://user-images.githubusercontent.com/7383162/117278312-8f550180-ae58-11eb-9ad3-0a9c8832aa75.png">

**Comment by RichardFoxBC** [comment]
Hi Karolis,

Yes I see what you mean about the images. I don't think we can use the final one (Marsh Fritillary) and the third one (Brimstone) isn't great either. I'll find some other images and drop them here

**Comment by RichardFoxBC** [comment]
![Common Blue male (Bob Eade)](https://user-images.githubusercontent.com/36193573/117287187-fe832380-ae61-11eb-8a45-bf040da44e47.jpg)

Would this be any better? If so, please use this on the third screen instead of the Brimstone

**Comment by RichardFoxBC** [comment]
This one any good for the final screen i.e. to replace the Marsh Fritillary image?
![Marsh Fritillary (Bob Eade)](https://user-images.githubusercontent.com/36193573/117290503-c978d000-ae65-11eb-8fe4-8ef960d2757a.jpg)

**Comment by RichardFoxBC** [comment]
How about this one for the first screen (replacing the Peacock image)?
![Orange-tip (Bob Eade)](https://user-images.githubusercontent.com/36193573/117317131-246bf080-ae81-11eb-8291-a6220f49ed6b.jpg)

**Comment by RichardFoxBC** [comment]
And might this one work for the final screen (replacing Marsh Fritillary)??
![Pearl-bordered Fritillary 2(Bob Eade)](https://user-images.githubusercontent.com/36193573/117317358-5c733380-ae81-11eb-9c1b-e5ad25f94c52.jpg)

**Comment by RichardFoxBC** [comment]
For the new onboarding screen, which I think should come between the "Submit and share your sightings" one and the "Your sightings will help protect..." one, I suggest the wording:

You can record a single butterfly or create a list of different species seen. 
Tap on the Record button to record a single species or hold the Record button down to start a species list.

**Comment by kazlauskis** [comment]
@RichardFoxBC Would a page like this be OK?

<img width="337" alt="Screenshot 2021-05-07 at 13 20 08" src="https://user-images.githubusercontent.com/7383162/117448736-02cd4080-af37-11eb-88ee-fb48be178e06.png">

**Comment by kazlauskis** [comment]
@RichardFoxBC Here is the new set of screens. Please close the ticket if these are OK.

<img width="338" alt="Screenshot 2021-05-07 at 13 30 22" src="https://user-images.githubusercontent.com/7383162/117450119-bdaa0e00-af38-11eb-8f3c-c3f6c495ea20.png">
<img width="334" alt="Screenshot 2021-05-07 at 13 30 27" src="https://user-images.githubusercontent.com/7383162/117450130-c00c6800-af38-11eb-813e-2b68baead46d.png">
<img width="344" alt="Screenshot 2021-05-07 at 13 30 32" src="https://user-images.githubusercontent.com/7383162/117450143-c39fef00-af38-11eb-9f33-b7dcd4124665.png">
<img width="346" alt="Screenshot 2021-05-07 at 13 31 48" src="https://user-images.githubusercontent.com/7383162/117450158-c7337600-af38-11eb-9394-2e2df09047a6.png">
<img width="340" alt="Screenshot 2021-05-07 at 13 32 45" src="https://user-images.githubusercontent.com/7383162/117450173-cac6fd00-af38-11eb-90ed-e3379f4eb76b.png">

**Comment by RichardFoxBC** [comment]
Happy with all of these except the Common Blue "Submit and share..." one.  The image is just too tightly cropped. Would this image work any better?
![Common Blue (Mark Searle)](https://user-images.githubusercontent.com/36193573/117456030-a91d4400-af3f-11eb-9c08-a3a73fe1f81b.jpg)

**Comment by kazlauskis** [comment]
Excellent, this last one fitted without any cropping. This is done now.
