### ISSUE TITLE
Image classification - symbols on photos and species names?

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#151]
When using the image classifier, the symbol in the bottom right of the photo thumbnail is a circle with an orange circle with a '!' inside when no species selected.  Even when the classifier is quite confident (100% in this example below as a Dark Green Fritillary).  When the species name is selected and matches, the symbol changes to a green tick if the classifier matches the name selected.  I found this a bit confusing at first. 

I think we need two types of symbol:
1. To indicate the confidence in the image classifier result.  This symbol should be on the photo
2. To indicate a match between the image classifier and the selected species.  Should this symbol be somewhere next to the selected species name?
![IMG_5519](https://user-images.githubusercontent.com/2699478/178748344-426c28d3-7fc7-4500-b09b-2bb01eb24b9a.PNG)

**Comment by Vilius-Stankaitis** [comment]
@DavidRoy Hi, I have updated mockup. Would this be more clear? 

https://projects.invisionapp.com/prototype/Butterflies-ckzflr6fm00qhtz01d0yejhpv/play/388c3d38

Potentially, we could add a new layout (Suggestions from your photos). Or extend layout with classifier result.

When no species is selected icons shows image classifier result. If species is selected then 
icons indicate a match between the image classifier and the selected species.

![Screenshot 2022-07-20 at 12.16.01.png](https://zube.io/files/nerc-ceh/66251e56b51ade92e59c2668d06c3a4c-screenshot-2022-07-20-at-12-16-01.png)
![Screenshot 2022-07-20 at 12.16.07.png](https://zube.io/files/nerc-ceh/532492e924b9b00d11b08e6f093b42ff-screenshot-2022-07-20-at-12-16-07.png)

![Screenshot 2022-07-20 at 12.15.56.png](https://zube.io/files/nerc-ceh/5660b9af65dd03de8466dba1418a523f-screenshot-2022-07-20-at-12-15-56.png)
![Screenshot 2022-07-20 at 12.16.12.png](https://zube.io/files/nerc-ceh/f7f96381b0afef8198c189e53ba3f3bf-screenshot-2022-07-20-at-12-16-12.png)

![Screenshot 2022-07-20 at 10.22.07.png](https://zube.io/files/nerc-ceh/834cc67642d5be9c47987ea9e700be55-screenshot-2022-07-20-at-10-22-07.png)

**Comment by DavidRoy** [comment]
Thanks.  That works well I think.

**Comment by kazlauskis** [comment]
@RichardFoxBC are you also OK with this?

@RichardFoxBC @DavidRoy Would you like to keep the AI suggestions as a separate list, e.g. "Suggestions from your photos" right above the "Flying now in your area" list (see the first screenshot) OR is it better to embed the AI likelihood results in the existing lists (see the second screenshot).

**Comment by DavidRoy** [comment]
@kazlauskis I might need this explaining, either when we meet next week or a quick zoom today or tomorrow.  

If I understand correctly, I prefer to have the AI results with the photo(s).  A symbol over the photo showing the %fit for the top species, then if clicking on the photo showing the full set of AI results (i.e. the last screenshot).  So no link to the 'Flying now in your area' list

The example of showing multiple species photos (of different species) - the second to last screenshot - is not realistic.  There may rarely be multiple photos but these would be of the same species.

Also how would this work with a photo added to a species list?

**Comment by kazlauskis** [comment]
Yeah, let's discuss this when we meet next week.

**Comment by RichardFoxBC** [comment]
This is all looking great! Only bug I can find is that the % likelihood from images for day-flying moths doesn't seem to appear in the species list. It works for butterflies but I tried it for Mother Shipton and Burnet Companion and although the image classifier worked fine, when I went to the species list, there was no % figure for these species

**Comment by Vilius-Stankaitis** [comment]
For the day-flying moths in the species list, a badge will appear when the image probability is above 70%. For the butterflies, it's 30%.

**Comment by RichardFoxBC** [comment]
Ah ok, thanks for the explanation. However, it is still not working. I've added a photo that the image classifier says is 100% Mother Shipton but no badge appears on that species in the species list

**Comment by Vilius-Stankaitis** [comment]
Thanks, this is the same issue as the #264 ticket. (not matching scientific names).
