### ISSUE TITLE
Remove day-flying moths from the "Species recorded" statistics

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#154]
On the statistics page, under "My totals", please filter out moth records from the "Species recorded (total)" and "Species recorded (2022)" values. I suggest we change the text to read "Butterfly species recorded (total)" and "Butterfly species recorded (2022)" if there is space. 

Moth records can contribute to the Records (total) and Records (2022) values.

**Comment by RichardFoxBC** [comment]
This isn't fixed in the app version that I'm testing v2.4.0 (211). There are still day-flying moths in the species report

**Comment by DavidRoy** [comment]
Same for me.  I have day-flying moths for both year and all-years reports

**Comment by Vilius-Stankaitis** [comment]
Sorry, please don't test the 211 build it's an old one. I will release the new version.

**Comment by RichardFoxBC** [comment]
Great! The day-flying moths have now gone from my species report, but they are still being counted in the species total - please can the species total (for the current year or all time) just include butterfly species and exclude day-flying moths?

**Comment by RichardFoxBC** [comment]
On the same screen, thanks for adding the word "Butterfly" to the species totals, but unfortunately this now displays as per the screenshot below for me, meaning that the important info i.e. "total" or "2022" is unreadable. Can this be adjusted please? There would seem to be plenty of room
![Image](https://user-images.githubusercontent.com/36193573/183600224-eb2ecb18-824e-4e16-af39-7c317269f66f.jpeg)

**Comment by kazlauskis** [comment]
@RichardFoxBC We can now filter out moths from all statistics pages. This also affects Records (total) and Records (2022) figures, which will show only butterfly record counts. Is that OK?

**Comment by RichardFoxBC** [comment]
What we agreed at the last meeting was to remove the moths from the Species totals but not from the Records totals. That's what I would prefer. Is that still possible please?

**Comment by kazlauskis** [comment]
No problem, we're working on it now. The app uses this one generic report which brings all the summarised stats. We can make two calls to fetch different stats and then combine these. A bit of sub-optimal from the mobile-data use perspective but the stats will be correct then.
