### ISSUE TITLE
What's New text and image

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#158]
I really like the "What's New" pop-up that appeared when I updated the app this morning. I assume that will be there for everyone and is not related to beta-testing? My only concern is with the (Clouded Yellow) image used in this pop-up. Where is that from and do we have permission to use it??

**Comment by Vilius-Stankaitis** [comment]
Yes, it will show for everyone who will update the app. I took the image from the species profile by © Philip Hambly who is mentioned in the credits. I hope this is alright.

**Comment by RichardFoxBC** [comment]
No I don't think we can assume that it is alright I'm afraid. Best to use a different photographer who I know we can use without having to check with them. Here are three seasonal and new images from Mark Searle, who provided lots of images for the app. Please use one of these
![Brown Hairstreak (Mark Searle)](https://user-images.githubusercontent.com/36193573/183610929-cc58167f-8261-4655-b72a-07cd8b9ede12.jpg)
![Scotch Argus (Mark Searle)](https://user-images.githubusercontent.com/36193573/183611037-0b743488-57fd-4aab-ae73-686d7cef964c.jpg)
![Chalk Hill Blue (Mark Searle)](https://user-images.githubusercontent.com/36193573/183611292-3189826c-5260-4437-878a-000579b9a386.jpg)
.

**Comment by Vilius-Stankaitis** [comment]
Thank you, I will replace the image.

**Comment by kazlauskis** [comment]
Oooh, these are nice pics, thanks!

We'll try to show the What's New pop up with future updates too. The idea is to refresh the pic every time. This gives us photos for +2 more updates 🙂

**Comment by kazlauskis** [comment]
@RichardFoxBC do you also want to credit Mark Searle below the pic in the new alert or is it enough to keep it on the credits page only?
