### ISSUE TITLE
Incorrect results from advanced_reports

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-butterflies-app#159]
The app uses `user-stats` report which returns both moths and butterflies stats for a given survey. The new requirement is to filter out moths from these results. Looks like the report has a `taxon_group_id` parameter but it isn't working as expected.

Fetching `https://irecord.org.uk/api/v2/advanced_reports/user-stats?survey_id=101` returns:

```
"projectRecordsCount": 808019
```

which seems to be correct. When we add `taxon_group_id=104` parameter (for butterflies), it filters species correctly but returns `projectRecordsCount` from other surveys too, no?

Fetching `https://irecord.org.uk/api/v2/advanced_reports/user-stats?survey_id=101&taxon_group_id=10` returns:

```
"projectRecordsCount": 9944020
```

**Comment by kazlauskis** [comment]
@johnvanbreda is this is something you could have a look at?

**Comment by johnvanbreda** [comment]
@kazlauskis the filters were set up for either survey_id or taxon_group_id, not both. I've applied a fix so let me know if that doesn't work.

**Comment by kazlauskis** [comment]
Thanks!
