### ISSUE TITLE
Issue: app went (and remains) blank after tapping record

### ISSUE THREAD

**Issue by Sam-Amy** [NERC-CEH/irecord-butterflies-app#167]
### Describe the issue

At first the app was unable to upload records- there's about six. Then when I tapped on the app I got a blank screen.

### Expected behaviour

Tapping the app should give me options like record and identity species.

### To Reproduce

Try to upload records

### App Version

Can't check as the app is blank

### Device

iPhone XS

### When did this happen

Problems began about 4 days ago (17/06/23)

**Comment by Sam-Amy** [comment]
Issue emailed to irecord@ceh.ac.uk

**Comment by Sam-Amy** [comment]
User has emailed to say it is working again

**Comment by Sam-Amy** [comment]
The same user has emailed again with the same problem. I also had something similar occur when I tried this morning (Samsung S21, iRecord Butterflies v2.5.1 (229)), but the screen only stayed blank/black for a few minutes and then after tapping quite a bit went back to the record page.

**Comment by kazlauskis** [comment]
What is this user's iRecord account ID? Also, do you know when the blank screens happened more precisely?

**Comment by Sam-Amy** [comment]
The issue just received from another user is described "Recently I have been troubled by the app reverting to a white screen and I have to restart my phone. I am using an iPhone with the latest operating system. I have reinstalled the app, but this hasn’t cured the problem. I do carry out complete restarts, but this hasn’t worked either." Details to follow.

**Comment by kazlauskis** [comment]
@Sam-Amy thanks for capturing these here, and sorry for me taking so long to get back to you, July has been super busy for us. I have fixed this problem now and the new app version is coming out shortly as v2.5.3.
