### ISSUE TITLE
Issue: Add green tick for verified records (feature request)

### ISSUE THREAD

**Issue by robin-hutchinson** [NERC-CEH/irecord-butterflies-app#169]
### Describe the issue

We have had a request from a user for green ticks for verified records to appear on iRecord butterflies as well. Is this easy to do?

### Expected behaviour

App to behave similarly to the general iRecord app when records are verified.

### App Version

Latest

**Comment by DavidRoy** [comment]
They should already do.  I certainly see them.  Can you ask the recorder to send an example of where this is not happening?

**Comment by robin-hutchinson** [comment]
Sorry, I thought this wasn't happening because I can't see them (screenshots from me, related to record https://irecord.org.uk/record-details?occurrence_id=29706173)

An example from the user is here: https://irecord.org.uk/record-details?occurrence_id=31645147

![93259](https://github.com/NERC-CEH/irecord-butterflies-app/assets/95474755/83824b72-43a9-4213-b552-887c6e6c0327)
![3748](https://github.com/NERC-CEH/irecord-butterflies-app/assets/95474755/cf8449ec-9678-42a8-a6c8-1f28c13c6ada)

**Comment by kazlauskis** [comment]
@robin-hutchinson, starting with v2.3.0, the iRecord Butterflies app checks for record updates every 15mins.

1. Which app version do you have?
2. Have you logged in using the same account from which you sent the records?
3. Is the device connected to the Internet?

**Comment by robin-hutchinson** [comment]
Thanks Karolis, I have version 2.5.2 and am connected to the internet and logged in! 

![iRecord Butterflies Version](https://github.com/NERC-CEH/irecord-butterflies-app/assets/95474755/8fc95964-eb85-403d-adbb-a53bff5e9226)

**Comment by robin-hutchinson** [comment]
Update from the user that reported this - they have green ticks for records before and after 17/07/2023, but not for that specific date even though the records are verified, so this may have been a one-off?

![image](https://github.com/NERC-CEH/irecord-butterflies-app/assets/95474755/4212f427-c50d-477b-9eb7-ede9526a41d4)

![image](https://github.com/NERC-CEH/irecord-butterflies-app/assets/95474755/c87007ab-320d-4a45-8ebd-b7375ddbbd63)

**Comment by kazlauskis** [comment]
@robin-hutchinson I have found and fixed a bug related to this. It won't fix these old record statuses but it should help prevent this. The new app version is coming out shortly as v2.5.3.

**Comment by robin-hutchinson** [comment]
Thanks Karolis, I'll let the recorder know!
