### ISSUE TITLE
App stopped working on mobile phone

### ISSUE THREAD

**Issue by zrandle** [NERC-CEH/irecord-butterflies-app#170]
### Describe the issue

One of our volunteers is using a Samsung SM-A105FN device and the iRecord butterflies app has stopped working on his mobile. 

### Expected behaviour

It to work

### App Version

the latest one

### Device

Samsung SM-A105FN

### Screenshots

<img width="209" alt="image" src="https://github.com/NERC-CEH/irecord-butterflies-app/assets/23524520/3c5aa5e3-f8cb-4203-9977-06fe021fc0c0">

**Comment by kazlauskis** [comment]
The minimum requirement for the app is a device with at least 3 GB of RAM. This particular device might not have enough RAM memory, and the Play Store prevents the download. Unfortunately, there is nothing we can do to help in this case. Please reopen the issue if that's not the case.

**Comment by zrandle** [comment]
Thanks for this. The recorder is confused because they "continue to run the generic i-Record app without difficulty, and have to use that for submitting butterfly records – less convenient but doable. Raises the question of RAM spec on the app – if I can run i-Record, why not i-Record Butterflies?!"

**Comment by kazlauskis** [comment]
Good question, this restriction is the same for the iRecord App too. I imagine the user has an older iRecord App version or may have installed it before the minimum RAM requirement was applied.
