### ISSUE TITLE
Add summary report

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-butterflies-app#18]
The current app has a summary report on the `My Account` page and it would be good to have something like that in the next app release. 

Unfortunately, for some reason, it doesn't always load and might be slow at times so a new report might be better. It seems like the current report in use is `library/totals/user_survey_contribution_summary.xml`(could be different though).

![IMG_1053](https://user-images.githubusercontent.com/7383162/109832241-14911f80-7c38-11eb-84d7-41289d4f2c3d.PNG)

**Comment by DavidRoy** [comment]
@johnvanbreda could you give your view on how feasible it would be to convert this report to ElasticSearch - library/totals/user_survey_contribution_summary.xml

even if only partly covering the existing functionality

**Comment by johnvanbreda** [comment]
@DavidRoy I think all the metrics except league position are easily achieved in Elasticsearch.

**Comment by DavidRoy** [comment]
@johnvanbreda could you switch the report over to ES in that case, as a quick fix to the main elements of the league table

**Comment by johnvanbreda** [comment]
Here's the body of a request to one of the REST API's ES endpoints, note that the created_by_id and year will need to be set appropriately. Also the outer query on website ID might not be necessary if handled by the authentication:
```json
{
  "size": "0",
  "query": {
    "bool": {
      "must": [{
        "term": { 
          "metadata.website.id": 23
        }
      }]
    }
  },
  "aggs": {
    "total-for-user": {
      "filter": { 
        "term": { 
          "metadata.created_by_id": 5
        } 
      }
    },
    "irecord-butterflies-filter": {
      "filter": { 
        "term": { 
          "metadata.survey.id": 101
        }
      },
      "aggs": {
        "user-filter": {
          "filter": { 
            "term": { 
              "metadata.created_by_id": 5
            } 
          },
          "aggs": {
            "species": { 
              "cardinality": {
                "field": "taxon.species_taxon_id"
              }
            },
            "year-filter": {
              "filter": { 
                "term": { 
                  "event.year": 2020
                } 
              },
              "aggs": {
                "species": { "cardinality": 
                  {
                    "field": "taxon.species_taxon_id"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Here's the response - I've annotated where each value is:
```json
{
  "took" : 176,
  "timed_out" : false,
  "_shards" : {
    "total" : 4,
    "successful" : 4,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 5493197, # total records for iRecord (all surveys)
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "total-for-user" : {
      "doc_count" : 6504 # total records in iRecord for this user
    },
    "irecord-butterflies-filter" : {
      "doc_count" : 510445, # total records for iRecord Butterflies app survey
      "user-filter" : {
        "doc_count" : 1149,  # total records for iRecord Butterflies app survey for this user
        "species" : {
          "value" : 66 # total species for iRecord Butterflies app survey for this user
        },
        "year-filter" : {
          "doc_count" : 1, # records for iRecord Butterflies app survey for this user in 2020
          "species" : {
            "value" : 1 # species for iRecord Butterflies app survey for this user in 2020
          }
        }
      }
    }
  }
}

```

@kazlauskis have you previously used Elasticsearch from any of the apps? If so should we re-use the same authentication, or use JWT?

**Comment by kazlauskis** [comment]
I haven't used Indicia ES for the apps yet. Unfortunately, the butterflies app will be linked to the old iRecord site which doesn't use JWT yet so some sort of proxy endpoint would have to be used for this.

**Comment by johnvanbreda** [comment]
@kazlauskis so if I add an end-point to the master branch of this API will that be the right approach? https://github.com/Indicia-Team/drupal-7-module-indicia-api

**Comment by kazlauskis** [comment]
It depends on how generic you are planning to set this up. If this is something for all apps then, yes, it would be a good place to put it. It already has a `report` endpoint for old-type reporting, so maybe something could fit next to it. If this is something for the butterflies app only then maybe creating a new branch for the app would be better.

**Comment by johnvanbreda** [comment]
@kazlauskis see https://github.com/BiologicalRecordsCentre/irecord-extras/issues/10 for information on the end-point, which integrates the new recorder metrics.

**Comment by kazlauskis** [comment]
Cool, it takes 300ms to get the report, I like it.

**Comment by johnvanbreda** [comment]
@kazlauskis There are 3 Elasticsearch requests:
1. Fetch the list of all species in the survey dataset, ordered by number of records.
2. Various aggregations for the user's data, e.g. first record, last record date, their list of species with number of records, their record and species counts.
3. A count of all records they've contributed to iRecord.

Request 1 can be a bit slow - over a second, so I cache that one. It only changes slowly anyway. So every few hours, you'll get a request that refreshes this query which takes a bit longer.
2 and 3 are fast. Plus a bit of PHP processing to calculate the rarity and other metrics.

**Comment by kazlauskis** [comment]
@johnvanbreda I am getting CORS errors. Can you add these headers to both OPTIONS and GET responses please?

<img width="566" alt="Screenshot 2021-03-19 at 11 44 12" src="https://user-images.githubusercontent.com/7383162/111775487-bc4d5500-88a8-11eb-8f72-29b838be02b1.png">

**Comment by johnvanbreda** [comment]
That's done now @kazlauskis

**Comment by kazlauskis** [comment]
@johnvanbreda Thanks, I am getting the new headers now. The requests still fails with 401, the reason is that preflight OPTIONS request by the browser will not include any custom headers. Can you also make it that the OPTIONS request didn't check for Authorization and X-API-Key headers?

**Comment by johnvanbreda** [comment]
Hopefully that's done - I don't have a quick way of testing, but an OPTIONS request just skips all the code now.

**Comment by RichardFoxBC** [comment]
Should the statistics be working now? My test version of the app was not returning any of the stats relating to test (and real) records that I've submitted so far in 2021

**Comment by kazlauskis** [comment]
No, the stats are hardcoded at the moment. You should be able to see it working with the next app update.
