### ISSUE TITLE
Stage

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#22]
Couple of comments on the "Stage" part of the recording process.

First I think we should have "Adult" as a default option rather than "not recorded" - I'd drop "not recorded" from the app completely if everyone else agrees

Second, and this is a bit picky, can we find a better icon for this field. I don't think the caterpillar that is currently being used is instantly recognisable as a caterpillar - it might be better if it was horizontally oriented rather than vertically, if we can find anything better

**Comment by kazlauskis** [comment]
I agree about the icon, I wasn't sure what best represents the stage. I will play around with this and see if I can get something better. 

I'm happy to default records to 'Adult'.

**Comment by RichardFoxBC** [comment]
I think a caterpillar is probably the best thing to have as an icon - I don't think there is space for a full life cycle, but I do think we need a caterpillar that is clearly a caterpillar

**Comment by kazlauskis** [comment]
@DavidRoy are you also OK defaulting the species to adults?

**Comment by DavidRoy** [comment]
Of course, Richard is the boss :-)

**Comment by kazlauskis** [comment]
Cool, just thought I should double-check.
