### ISSUE TITLE
Error message in My Surveys

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#23]
I also have to report that I see to have accidentally driven my test app into a dead end. I get the attached error message on the My Surveys screen which I can't seem to get out of - I can't display either the pending or uploaded records.

![IMG_6659](https://user-images.githubusercontent.com/36193573/111650502-450eb700-87fd-11eb-811a-793b17809054.PNG)

**Comment by kazlauskis** [comment]
Good testing! 😄 Thanks, I will have a look at it.

**Comment by RichardFoxBC** [comment]
Happy to oblige! I'm stuck now - guess I'll have to delete and reinstall the app?

**Comment by kazlauskis** [comment]
I've fixed this now. The issue has occurred when a record was deleted before the GPS lock was acquired. No need to delete the app, the next app update will fix it for you - reopen the ticket in case you still have this issue.
