### ISSUE TITLE
Photo submission

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#24]
I thought that I had successfully attached and submitted a photo with one of my records using the app yesterday. However, when I look at the record on the iRecord website there is no sign of the photo.

**Comment by DavidRoy** [comment]
Photos lacking from my submissions too. e.g. https://www.brc.ac.uk/irecord/edit-generic-record?occurrence_id=20069041

**Comment by kazlauskis** [comment]
The photos were attached to the sample instead of occurrence - I've fixed this now.
