### ISSUE TITLE
Do we need to capture data source?

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#25]
The current app captures the device used to submit records, e.g. iOS, android, website

The new version does not submit to this attribute

**Comment by RichardFoxBC** [comment]
Interesting one. I don't think I've ever used this information for anything, but not sure if UKCEH have? I guess if it is easy to implement then why not include it?

**Comment by DavidRoy** [comment]
Rarely used but worth capturing to confirm we prioritise android and iOS equally.
@kazlauskis is this ok for you to include.  

Current breakdown.
273	144	2398	"iOS"	"189709"
273	144	2399	"android"	"146605"
273	144	2396	"website"	"13"

**Comment by kazlauskis** [comment]
That's done now. 

Like we do in some other apps, I have also added the app-version (`smpAttr=1139`) to samples. It should help identify records coming from different app releases which may submit data differently.
