### ISSUE TITLE
Uploaded species list survey should point to an iRecord record details page

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-butterflies-app#26]
For a single species record, there is a dedicated page available that allows viewing a record without the user having to log in.
Example: https://www.brc.ac.uk/irecord/record-details?occurrence_id=20073090

At the moment, in the app we point multi-occurrence records to an **editing** form: https://www.brc.ac.uk/irecord/enter-record-list?sample_id=ID

@johnvanbreda Is there a page on the iRecord site for **viewing** multi-occurrence records?

**Comment by johnvanbreda** [comment]
No, though it would not be hard to setup. @DavidRoy please advise on how this fits in with other priorities?

**Comment by DavidRoy** [comment]
@johnvanbreda please go ahead as a high priority for the app that is close to release.  A general sample-details view would also be worth considering

**Comment by johnvanbreda** [comment]
@DavidRoy Ok - please can you let me know roughly what you'd expect to see on this page? Is it just a filtered records grid, or does it need a map as well? Same default columns as the Explore page or something different?

If we provide this for the app, it can easily be multi-purpose.

**Comment by DavidRoy** [comment]
@johnvanbreda how about a filtered records grid with a map?  Similar to the explore page but with the relevant sample attributes?

**Comment by kazlauskis** [comment]
This is going to be a single sample with multiple occurrences so the map should be similar to the one used on the `record-details` page.

**Comment by johnvanbreda** [comment]
Ok, here's an example of the new page - is this OK? https://www.brc.ac.uk/irecord/sample-details?sample_id=13983489

**Comment by kazlauskis** [comment]
Thanks! Looks very good, do you think it is possible to open this up to non-authenticated users like the `record-details` allows?

**Comment by johnvanbreda** [comment]
That's done.

**Comment by kazlauskis** [comment]
Cheers 👍
