### ISSUE TITLE
Upload all option

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#28]
It would be good to have an Upload all option on the My Surveys page, in case users have lots to upload

**Comment by DavidRoy** [comment]
@kazlauskis is this planned for the first live version?

**Comment by kazlauskis** [comment]
It depends on when you want the first live version released, I could add this sometime next month.

**Comment by RichardFoxBC** [comment]
I've already had feedback from one tester wanting an Upload all button!

**Comment by DavidRoy** [comment]
Include upload all button when more than 5 records to submit?
