### ISSUE TITLE
Filter confusion

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#31]
Perhaps its just me, but when I start typing into the search box I'd be expecting to filter on species. So when I type in "brown" I am surprised and confused that what comes up on the screen is stuff about the brown colour filter and the browns group filter - I can see the species that I want to get to (with "brown" in their name) behind all this stuff but don't find it intuitive to get to them

**Comment by kazlauskis** [comment]
Thanks, that's a good point. When searching for a species, after you have finished typing the name tap on the blue `Done` button on your keyboard and this will then close the search and show the species matching your text. I will also make the smaller 'Done' in the top header behave the same, at the moment, that only closes the search. Does this make sense?

![IMG_F8E58D839F92-1](https://user-images.githubusercontent.com/7383162/113217922-8a5bcb80-9276-11eb-99c6-95f18b79d64f.jpeg)
