### ISSUE TITLE
UK Status 

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#33]
I'm going to redo the text for all species in the "UK Status" field. This is in part to reflect BC's new conservation priorities and/or threat levels. However, I also feel that the inclusion of "restricted distribution" or "widespread" in this text for each species isn't very helpful to the user (especially when there is a map just below) and isn't really about the species' UK status. Everyone happy if I ditch the "restricted distribution"/"widespread"?

**Comment by DavidRoy** [comment]
yes, happy to leave the guide completely in your capable hands

**Comment by RichardFoxBC** [comment]
OK I've finished my edits now. I'll leave the issue open for now, Karolis you can close it when the changes have been implemented in the app
