### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#34]
Beta invitation links:

- For **Apple** devices (iPhones, iPads): https://testflight.apple.com/join/NMGzVoUs
- For **Android** devices: https://play.google.com/apps/testing/com.natural_apptitude.butterfly

**Comment by DavidRoy** [comment]
Still hunting for the android certificate.  I'll chase again!

**Comment by kazlauskis** [comment]
@RichardFoxBC this is the link for iOS Beta testing: https://testflight.apple.com/join/NMGzVoUs

**Comment by RichardFoxBC** [comment]
Is that iOS testing link specific to a particular version of the new app or just to whatever the latest version is that you've pushed?

**Comment by kazlauskis** [comment]
Correct, that always points to the last version.

**Comment by DavidRoy** [comment]
@kazlauskis can you add the link for android testing to this issue?

**Comment by kazlauskis** [comment]
Done, I've added the links to the ticket description.
