### ISSUE TITLE
Records with only Lat/long

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#36]
Please amend the text warning when a record only has a lat/long location to read: 

Your location is not in the UK, Republic of Ireland, Isle of Man or Channel Islands. Please tap on Location to change if necessary.

Also because this warning message is not very big on screen, I wonder if we need a second line of defence? Would it be possible to have a warning on it on the My Records screen somehow too?

**Comment by kazlauskis** [comment]
Done this now.
<img width="326" alt="Screenshot 2021-04-01 at 18 34 36" src="https://user-images.githubusercontent.com/7383162/113332437-14f50700-9319-11eb-9b3a-901b9543ea66.png">
<img width="328" alt="Screenshot 2021-04-01 at 18 34 40" src="https://user-images.githubusercontent.com/7383162/113332442-16263400-9319-11eb-9430-ce1d36a21169.png">
