### ISSUE TITLE
App store screenshots

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-butterflies-app#38]
@RichardFoxBC do these screenshots and titles look OK to you?
![Simulator Screen Shot - iPhone 8 Plus - 2021-03-25 at 11 17 57_record_framed](https://user-images.githubusercontent.com/7383162/113351813-4d094380-9333-11eb-9861-8438efd888a9.png)
![Simulator Screen Shot - iPhone 8 Plus - 2021-03-25 at 11 19 18_survey_framed](https://user-images.githubusercontent.com/7383162/113351820-4ed30700-9333-11eb-8dec-06b5577ebf87.png)
![Simulator Screen Shot - iPhone 8 Plus - 2021-03-25 at 11 19 44_guide_framed](https://user-images.githubusercontent.com/7383162/113351823-4f6b9d80-9333-11eb-9f10-406f643f533f.png)
![Simulator Screen Shot - iPhone 8 Plus - 2021-03-25 at 11 20 02_search_framed](https://user-images.githubusercontent.com/7383162/113351825-509cca80-9333-11eb-93ad-cf9e5afa4a89.png)
![Simulator Screen Shot - iPhone 8 Plus - 2021-03-25 at 11 20 37_location_framed](https://user-images.githubusercontent.com/7383162/113351827-51356100-9333-11eb-9dd7-0a9e21149723.png)
![Simulator Screen Shot - iPhone 8 Plus - 2021-03-25 at 11 22 40_species_framed](https://user-images.githubusercontent.com/7383162/113351831-52668e00-9333-11eb-82e5-3eb07fba9d87.png)
![Simulator Screen Shot - iPhone 8 Plus - 2021-03-25 at 11 24 14_photo_framed](https://user-images.githubusercontent.com/7383162/113351832-52ff2480-9333-11eb-8316-9be31750d3a4.png)

**Comment by RichardFoxBC** [comment]
Hi Karolis, these look great, many thanks. My only suggestions are re the final one - perhaps change the title to "Adult and life cycle photos" and  use a larval image to make the point clearly? One that has a portrait orientation image e.g. Comma or Dark Green Fritillary would be good
