### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-butterflies-app#4]
User feedback from a new user at 6 September 2020:

1) from the screen, it was clear how to select species identified but not how to add them and the number seen to complete the submission.  To do this I discovered you have to ‘open up’ on each butterfly by name and then select.  Not obvious or I suggest a required step.  One should be able to identify & number from a single screen.

2) Date - I tried changing the date but it kept defaulting to today’s date. My sightings were in the 5th September 2020.

3). Location - it took several attempts to get this to work but I got there in the end.

So I love the idea but anything which eases the use of this app would be most welcomed.  The recent UK butterfly count app by comparison was very easy to use.

**Comment by kitenetter** [comment]
I'm unable to replicate the problems described.

**Comment by kazlauskis** [comment]
This will be now irrelevant in the new app version.
