### ISSUE TITLE
Stats refresh

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#40]
Do the statistics page not refresh automatically? If not, I think it should. 

Having the refresh button on the page is good, but I think users would expect it to update automatically from time to time, at least each time you reopen the app.

**Comment by kazlauskis** [comment]
It doesn't yet and I agree this should be improved. In general, we should spend some more time redesigning the stats page.

**Comment by DavidRoy** [comment]
Auto-refresh every time and pull-down refresh

**Comment by kazlauskis** [comment]
@RichardFoxBC just want to clarify if this is correct:

1. The stats page will refresh every time it is opened from the Menu
2. We will remove the 'Refresh' button and introduce a pull-down refresh action.

**Comment by RichardFoxBC** [comment]
Sounds good to me @kazlauskis 

If we're going to get rid of the Refresh button, we'll probably need a message on the page that says "swipe down to refresh statistics"

**Comment by kazlauskis** [comment]
Like a one-off message that can be dismissed?

**Comment by RichardFoxBC** [comment]
No I was thinking more of a permanent bit of text on the page

**Comment by kazlauskis** [comment]
OK, will do. The pull to refresh action is a common pattern that most people should know about though - it is the default way to update lists on Android and iOS but if this audience needs some help with this then a bit of text might not be too bad.
