### ISSUE TITLE
App rating pop-up

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#42]
How often does the pop-up asking people to rate the app appear? I do find such things annoying when I am using an app, so I wouldn't want it to appear too often.

**Comment by DavidRoy** [comment]
@kazlauskis please advice on any plans on this for version 1.  
@RichardFoxBC Maybe a one-time 'ratings' pop-up after 5 records have been submitted?

**Comment by kazlauskis** [comment]
It appears only once and only after the user has already had 10 sessions with the app.

**Comment by DavidRoy** [comment]
@RichardFoxBC This seems a good approach.  Close this issue if you agree
