### ISSUE TITLE
Map remembering location

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#43]
When I am testing by creating lots of dummy records but not uploading them, I find that the map has to refind my location from scratch for each consecutive record in the same session. It is quite time consuming waiting for it each time and I would expect it to remember where I am from one record to the next in the same session. Is this because I've not uploaded the records? Would it remember my location if I uploaded a record or does it just start from scratch each time?

**Comment by kazlauskis** [comment]
This depends on the device. In general, once you have had your first GPS lock then this should be under 30s to get new locations for subsequent records. We can add some location caching but it is hard to know what is a 'session', if we base it on time then the user can travel a long distance within 2 mins of the app use (if on a bike or running or whatever). For me, acquiring fresh new locations is near-instant but that will vary from device to device.

**Comment by RichardFoxBC** [comment]
OK lets leave it as it is for now. But, I think this makes it even more important that people get into the habit of clicking the location icon (whichever one we decide on) when they are on the map page to make sure their new sighting is at their current location not at a previous one. So, even more important that we have a pop-up message explaining the icon and suggesting that people click on it to get their location for each sighting.

**Comment by kazlauskis** [comment]
The user shouldn't require to tap the GPS button, the GPS is run every time a new record is created. Since we don't cache the location it should be fresh for each record.

**Comment by DavidRoy** [comment]
Can this issue be closed or do we need to review options for this, for the next version?
