### ISSUE TITLE
Checking probability scores and setting an appropriate threshold

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#44]
Some of the species appearing in the "Flying now in your area" list are inappropriate and could lead to increased incorrect IDs by inexperienced users and a loss of faith in the product by experienced butterfly recorders. I think we first need to check that the rules are being correctly implemented in the app. As explained by email, I cannot see how Small Skipper appeared in my list last week and I wonder if my list is being drawn from the wrong region. Then we need to set an appropriately conservative threshold so that species are not appearing in the Flying now list weeks or months ahead of when they might actually be encountered.

This really needs to be done before wider testing of the app and certainly before release.

**Comment by kazlauskis** [comment]
@RichardFoxBC I agree, we should introduce some cutoff threshold for low probability species. Let me know what you want the threshold to be. It would be useful if you could attach some screenshots of the old and new app species lists in case you find there are any inconsistencies.

**Comment by DavidRoy** [comment]
@RichardFoxBC The regions for the flight periods are by country (England, Wales, Scotland, Northern Ireland).  I think the issue is that we are not applying the cutoff as in the previous app.  In week 16 in England, Small skipper has a flight period probability of 0.0000761797.

@kazlauskis can you see the cut-offs used in the old app?  Are they applied to the final likelihood score and/or the separate geographic or time likelihoods?

**Comment by RichardFoxBC** [comment]
Ha! And there was me thinking that E, W, N, S must have been east, west, north, south. I'd never realised that the UK countries were the same as the compass point before!

**Comment by kazlauskis** [comment]
@DavidRoy as far as I can tell from the old app, the cut-off threshold that was used is `0.001` and it was applied to the final calculated likelihood (i.e. "here and now" list).

**Comment by DavidRoy** [comment]
@RichardFoxBC it caught me out too!
@kazlauskis that cut-off matches my testing of the lists on the old vs new app

@RichardFoxBC shall we agree to reinstate the cut-off of 0.001?

**Comment by RichardFoxBC** [comment]
Yes let's reinstate the cut-off and see what impact that has during testing

**Comment by kazlauskis** [comment]
I've added the threshold now. Any species from "here and now" with probabilities below `0.001` will be pushed to the "here other times of year" list. The Beta update should be ready for sometime today.
