### ISSUE TITLE
Add day-flying moths to species list and guide

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#5]
- [x] Add warehouse ids
- [x] Show when to find species text if no lifechart
- [x] Show a moth thumbnail if no image

**Comment by DavidRoy** [comment]
Not required for version released in April 2021.  Longer term aim to include but details of implementation to be agreed.
Revisit with a discussion and mockup when time allows

**Comment by DavidRoy** [comment]
@RichardFoxBC to discuss with BC colleagues
Define list of species to include
Build probability/likelihood filters
Decide how many species to include in guide - needs photos, maps, text, phenology plot
Switched off by default to not confuse inexperienced recorders (i.e. within app settings)

**Comment by RichardFoxBC** [comment]
@DavidRoy here is my starting list of 30 moths (and in some cases their caterpillars) to be added to the app. These are all deemed likely to be seen during butterfly recording and where there isn't any major ID confusion. Let me know if you have any concerns about any of them:
Six-spot Burnet
Oak Eggar
Fox Moth
Emperor Moth
Hummingbird Hawk-moth
Shaded Broad-bar
Silver-ground Carpet
Yellow Shell
Common Carpet
Chimney Sweeper
Grass Rivulet
Magpie Moth
Latticed Heath
Brown Silver-line
Speckled Yellow
Common Heath
Vapourer Moth
Clouded Buff
Scarlet Tiger
Jersey Tiger
Cinnabar
Small Purple-barred
Burnet Companion
Mother Shipton
Silver Y
Small Yellow Underwing
Antler Moth
Beautiful Yellow Underwing
Gold Swift
Bordered White

**Comment by DavidRoy** [comment]
@RichardFoxBC no objection to these and this is a tricky one.  some other random suggestions of species to consider:
Mint moth (Pyrausta aurata)
Forester moth (Adscita statices)
Argent and sable moth (Rheumaptera hastata)
Small Magpie (Anania hortulata)

Maybe you discounted these because of ID confusion?

Did Ian also look at what gets recorded regularly on transects?

**Comment by RichardFoxBC** [comment]
Thanks David. We have excluded Forester and Argent and Sable so far because of both rarity and ID difficulties. Hadn't really thought about micros - that might open a whole other can of worms!

**Comment by DavidRoy** [comment]
Agreed. Let's start with your list as that certainly covers the main things likely to be found and id'd by butterfly recorders

**Comment by RichardFoxBC** [comment]
@kazlauskis I've uploaded photos of the 30 moth species that we will start with. Do you want me to enter the text and details for them into the same species.xlsx spreadsheet as the butterflies? i.e. just continue the list. Or do you want the moths separated off in some way - as we will be allowing the user to switch them on and off as a group.

**Comment by kazlauskis** [comment]
Thanks! Yes, please use the same sheet. You can just append the moths to the end of the butterflies list but maybe create a new column and flag the new species as moths.

**Comment by RichardFoxBC** [comment]
I've now added text for the 30 day-flying moths to the Species spreadsheet. Because we don't have life-cycle diagrams for the moths, I've described the flight season, which you can hopefully display in the app under "When to see" for the moth species.

**Comment by kazlauskis** [comment]
@RichardFoxBC Excellent thanks. We don't have the moth distribution maps yet or did I miss them somewhere?

@DavidRoy for the moth warehouse IDs, I think, originally you might have set up the IDs for the butterflies. Is there a special warehouse butterflies+moths list we should use for this or should I just use the IDs from the UKSI master list in the warehouse?

**Comment by RichardFoxBC** [comment]
@kazlauskis no we don't have the maps yet. Nor the cut-outs that are needed for the buttons - those could take some time

**Comment by RichardFoxBC** [comment]
Hi @kazlauskis I've just uploaded the moth cut-outs into a new folder "Cutouts - moths". Hope these are OK for you to use in the app.

**Comment by kazlauskis** [comment]
Great! We'll add these in.
