### ISSUE TITLE
Location box text truncated

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#55]
One tester reported that on the location entry page, the text "Site name e.g. nearest village" was truncated on their device to "Site name e.g. nearest villa". 

Karolis - please implement the solution you described in our meeting today

**Comment by kazlauskis** [comment]
I find it hard to reproduce this issue. The location name placeholder is truncated correctly with ellipses on small devices. Would it be possible for this person to send us a screenshot of the page? Or at least confirm that the ellipses are missing from the placeholder.

<img width="304" alt="Screenshot 2021-05-07 at 12 35 14" src="https://user-images.githubusercontent.com/7383162/117444056-d57d9400-af30-11eb-99ff-2dd41a0a046d.png">

**Comment by RichardFoxBC** [comment]
I'm not too worried about whether the ellipses are there or not. The problem is that if there is no way of reading the missing text, it doesn't make sense as "nearest villa..." So what (if anything) can we do? Can we move the text to the left a bit i.e. reduce the space between the icon and "Site"? Or could we put "e.g. nearest village in smaller size type than "Site name" to make it fit?

**Comment by kazlauskis** [comment]
Is there some shorter text we could think for this?

**Comment by RichardFoxBC** [comment]
Not really. I had tried to think of alternatives when I replied earlier. Only thing I can think of is to replace "nearest" with "nearby" but it only saves 1 character. We could drop the full stops from "e.g." so that it is just shown as "eg"?

**Comment by RichardFoxBC** [comment]
I'd rather have village. Many records will be a long way from a town and this instruction would lead to incorrect and unhelpful site names. Will it not fit if we have "Site name eg nearby village"

**Comment by kazlauskis** [comment]
OK, I've done that now.
