### ISSUE TITLE
Stopping the location name box cutting spaces

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#59]
We didn't talk about this issue at today's meeting and I'm not quite sure how we left it after the last meeting. This is where the app sometimes removes a space that you've put in between words in the location name box. Would be good to fix this as it is a bit annoying and will introduce unnecessary errors into location names.

**Comment by kazlauskis** [comment]
Thanks, I have fixed this one this morning and I will push the update with the other changes sometime tomorrow.
