### ISSUE TITLE
How to delete a record message

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#60]
After emails yesterday from a tester who couldn't work out how to delete records from the My Records page, I've done some more testing and think that there is a problem with the information messages. If I reset my copy of the app, when I create a first incomplete record and look in My Records, I see the message "To delete any surveys swipe it to the left". However, if I then complete the record, this message is no longer shown but is replaced by the message "Please do not forget to upload any pending surveys!". The message telling the user how to delete doesn't reappear no matter what I do from that point onwards (e.g. adding further incomplete or complete records), so it is not surprising that the tester couldn't work out how to do it.

I think this needs to be fixed. Indeed, I don't think the beta was functioning like this perviously - I thought that the delete message was there all the time, but I might be imagining things. 

Let me know if you need more info (screenshots etc) Karolis. Given that we will have an upload all button shortly, if there is some conflict caused by having two different information messages here, I would certainly favour keeping the delete one rather than the remember to upload one.

**Comment by kazlauskis** [comment]
Thanks, I'll make sure the delete tip appears in the Uploaded tab after the user uploads a record.

**Comment by RichardFoxBC** [comment]
Thanks Karolis. That would be good to have it on the Uploaded tab, but it should remain on the Pending tab too (not disappear as it currently does). Indeed, it is more important on the Pending tab as that is where accidentally created records (e.g. when people have touched the Record button by mistake) will be sitting.
