### ISSUE TITLE
Update Play Store feature graphics

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-butterflies-app#63]
The old graphics represent the old app so it would be good to get something up to date instead.

<img width="684" alt="Screenshot 2021-05-07 at 16 31 41" src="https://user-images.githubusercontent.com/7383162/117474811-3c13a980-af53-11eb-8f9f-9be608d96676.png">

**Comment by RichardFoxBC** [comment]
The iOS app store only has screen shots of the app, and I was assuming, Karolis, that you would be able to submit some new screenshots to replace those.

I see that you've already done that on the Google Play store, as well as updating the text. Many thanks!

I don't have the skills to create a new graphic like the one you've shown above, so I guess for now we just need to make sure this old style one is deleted.

**Comment by kazlauskis** [comment]
Yes, the new screenshots will appear in both app stores. Play Store won't let us publish the app without the feature graphic so I will replace it with some very basic placeholder for now then. We can reopen the ticket in case we want to design something better.
