### ISSUE TITLE
Bug! 

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#64]
Hi Karolis, afraid I've found a bug in the new release (63). From a brand new install on iPhone 8, I did the following:

1. Give permission to access location while using app
2. Go through the onboarding screens
3. Click OK to the Adding Observations popup
4. Long tap the Record button and select Species list
5. When species list screen opens, click Back without entering anything
6. Short tap the Record button to start a single species record. Add species and location details, then click Finish
7. This gives a red "Oops! Something, went wrong" warning 

This is a reproducible bug for me on my device.

The issue seems to be that while you cannot start a new single species record if there is already an incomplete one in your My Record pending, you can start a new single species record if there is an incomplete Species List in My Records pending.

Also, as a very minor point, please delete the comma between "Something" and "went wrong" in the error message.

Hope this isn't a difficult issue to fix.

best wishes
Richard

**Comment by kazlauskis** [comment]
Yes! I can reproduce this, thanks for the details, I will fix it asap.

**Comment by kazlauskis** [comment]
I have fixed this one and the app update should reach you shortly.
