### ISSUE TITLE
Bug! App freezes if use bracket in location name field

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#65]
Hi Karolis, a tester reported this morning that the current beta (64) froze (blank screen and needed to exit app) if they tried to put a bracket into a site name. This was on an Android phone, but I've just replicated it on my iOS phone. Same issue exists for square brackets [ and ], and also \

**Comment by kazlauskis** [comment]
Thanks, I'll look into this now.

**Comment by kazlauskis** [comment]
I've fixed this now and pushing a new next app update.
