### ISSUE TITLE
Enhanced statistics page

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#71]
priority 1 - expanding current page
Species list for current year and total.  Click on statistic (e.g. species recorded 2021 or total) to show list of species
Expand to number of records per species and/or number of individuals 
Year selector for statistics
Position in league tables (current year as the priority) for records and species

[Database call with parameter of year and user]
Look at options for improving the design of page

@DavidRoy discuss database reports with JvB

priority 2 - simple graphical options
change in ranking through time?

**Comment by DavidRoy** [comment]
@johnvanbreda - could we meet to discuss the feasibility of implementing these reports

**Comment by johnvanbreda** [comment]
Yes, let me know when is good for you @DavidRoy

**Comment by johnvanbreda** [comment]
Some notes 
- Species list for current year and total is fairly easy (Elasticsearch report). 
- Number of records can use sum aggregation, perhaps treating missing values as 1 (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-sum-aggregation.html#_missing_value_17)
- Position in league tables is hard to do in pure Elasticsearch. It may be necessary to dump the table of recorders and counts into a temporary table then use PostgreSQL's `row_number() over` to find the position.
- Change of rank over time will be tricky - we may need to snapshot multiple versions of the recorders/counts data, add rank data, then either keep in PostgreSQL or push back into Elasticsearch.

**Comment by DavidRoy** [comment]
Restrict to app survey for now, maybe widen to all iRecord app/website submissions.

Table:
species name, number of records (record count), sum of individuals counted (sum of counts)

with sort option on all columns

Default = current year
Option to select 'all years'
Option to select individual year

**Comment by DavidRoy** [comment]
From current stats page:
Click on row = Species recorded (total)
Opens a report pages with the table (see comment above for specification) and defaults to all year summary

Click on row = Species recorded (2021)
Opens the same report page with table, but defaults to current year

The report page with table enables options to select all years or a specific year.

**Comment by DavidRoy** [comment]
@johnvanbreda can you prioritize the report/API to support these initial statistics for the app.  If possible, having them ready by the beginning of next week.  Please liaise with @kazlauskis for details

**Comment by johnvanbreda** [comment]
@kazlauskis I've made several changed in the Drupal 7 Indicia-api develop branch to support extra reporting options. I'll email you some rough documentation (as I'm not sure how to update Postmaster).

Is it OK to merge develop to master and make it live, or do you have a test setup environment we can try it on first? The existing end-point under advanced_reports should in theory not have changed, but the code was refactored a bit.

**Comment by kazlauskis** [comment]
Thanks. Once the iRecord migrates to the Drupal 8+ these changes will probably have to be applied to the DP8 module too. Feel free to merge the changes to master, as long as it is backwards compatible I don't really need to review this. We will be discontinuing this module in favour of direct communication to the Warehouse with the new JWT authentication.

**Comment by kazlauskis** [comment]
A few screenshots from the mockup. I haven't implemented this yet so can easily change if you have any suggestions.

<img width="393" alt="Screenshot 2021-07-07 at 11 47 09" src="https://user-images.githubusercontent.com/7383162/124747622-06bb1600-df1a-11eb-855f-c224de02d923.png">
<img width="388" alt="Screenshot 2021-07-07 at 11 47 22" src="https://user-images.githubusercontent.com/7383162/124747628-0884d980-df1a-11eb-976f-d28a57f3ba8c.png">

**Comment by RichardFoxBC** [comment]
@kazlauskis The mock-up looks great! Hopefully you can get it working with the real report shortly.

Assuming that the report being done by @johnvanbreda  only includes butterfly records submitted through the iRecord Butterflies app, then @kazlauskis please add the following text to the Species report page: Currently, this report only includes records that you have submitted through the iRecord Butterflies app and not other butterfly records that you have uploaded to iRecord via other routes (e.g. UKBMS).

**Comment by DavidRoy** [comment]
Looks great
@johnvanbreda - are you ok providing the reports?

**Comment by johnvanbreda** [comment]
Yes, of course.
@kazlauskis the new report API endpoints are now live as per the documentation I provided via email.

**Comment by kazlauskis** [comment]
Thanks!
