### ISSUE TITLE
Feedback verification decisions within the app

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#72]
when open the app, recieve in-app push notification to alert recorders of comments available
(i.e. 5 surveys have feedback)
uploaded list shows symbol (?, x, tick)
view record/list.  Link to edit record

First step = @kazlauskis to produce mock-up

medium if re-using approach in Bloomin' algae app

Query for new verification data every 15mins:
**Method**: POST
**URL**: https://warehouse1.indicia.org.uk/index.php/services/rest/es-occurrences/_search
**BODY**: 
```JSON
{
    "size": 10,
    "query": {
        "bool": {
            "must": [
                {
                    "match": {
                        "metadata.survey.id": SURVEY_ID
                    }
                },
                {
                    "bool": {
                        "should": [
                            {
                                "match_phrase": {
                                    "identification.verification_substatus": "1"
                                }
                            },
                            {
                                "match_phrase": {
                                    "identification.verification_substatus": "2"
                                }
                            },
                            {
                                "match_phrase": {
                                    "identification.verification_substatus": "3"
                                }
                            }
                        ]
                    }
                },
                {
                    "range": {
                        "metadata.updated_on": {
                            "gte": TIMESTAMP
                        }
                    }
                }
            ]
        }
    }
}
```

> Some extra notes from David:
  1.  Use cache_occurrences.record_status and cache_occurrences.query to automatically create verification message (red text on mockup).  Show where record_status is (V or R).  Find these fields in Elastic Search?
  2.  For lists, show number of species by verification status in coloured boxes: green (=V), red (=R), orange (=Query is True), grey (record_status = C and query is null)? Find these fields in Elastic Search?
  3.  For ‘see more’ button, show record comment (e.g. comment on this record<https://irecord.org.uk/record-details?occurrence_id=23621379> from verifier Kat Dahl). Find these fields in Elastic Search?  Also include link to full record-details page via iRecord website link?

**Comment by kazlauskis** [comment]
This is what we've done in the Bloomin' Algae app. The app checks for any new verified records every 10mins. We could follow a similar design here or change it. We could also show verifier comments somewhere.

![image001](https://user-images.githubusercontent.com/7383162/118242938-c7ca9000-b495-11eb-838b-f340d371908a.png)
![image002](https://user-images.githubusercontent.com/7383162/118242943-c9945380-b495-11eb-83fc-380d251877ac.png)
![image003](https://user-images.githubusercontent.com/7383162/118242953-cbf6ad80-b495-11eb-9e1e-03bf58088103.png)
![image004](https://user-images.githubusercontent.com/7383162/118242960-cdc07100-b495-11eb-89a4-2417666fd6e4.png)

**Comment by DavidRoy** [comment]
Next step is to mock-up the user interface.  To cover lists and individual occurrence notifications

**Comment by kazlauskis** [comment]
This is what is currently included about the verification in the Elastic occurrence output (`services/rest/es-occurrences/_search`):
```
 "identification": {
    "verification_substatus": "2",
    "verification_status": "V",
    "verification_decision_source": "H",
    "verified_on": "2022-01-26 09:48:26.000",
    "verifier": {
      "name": "Surname, Name",
      "id": "1234"
    },
    "auto_checks": {
      "enabled": "true",
      "output": [],
      "result": "true"
    }
  },
```

This is what's included if the occurrence is fetched directly (`services/rest/occurrences/OCCURRENCE_ID?verbose=1`):
```
{
  "verified_on": "2022-01-26T09:48:26+00:00",
  "verified_by_id": "1234",
  "record_status": "V",
  "record_substatus": "2",
  "last_verification_check_date": "2022-01-22T18:52:25+00:00"
}
```

None of the endpoints contain any occurrence comments and we could build a new report to fetch these but I would hope this could be added to one of the REST endpoints instead. Or maybe a new `services/rest/occurrence_comment` endpoint.

**Comment by DavidRoy** [comment]
@burkmar can you help Karolis with an API update to enable access to verifier comments, e.g. to enable Karolis to access a comment like 'Thank you very much for submitting your record! Lovely clear photos!' from this record https://irecord.org.uk/record-details?occurrence_id=23621379
So we can report this back in the iRecord Butterflies app

**Comment by DavidRoy** [comment]
@burkmar can you help Karolis with an API update to enable access to verifier comments, e.g. to enable Karolis to access a comment like 'Thank you very much for submitting your record! Lovely clear photos!' from this record https://irecord.org.uk/record-details?occurrence_id=23621379
So we can report this back in the iRecord Butterflies app.

I don't think this information is held within the elasticsearch index?
