### ISSUE TITLE
Integrate image classification suggestions in-app

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#73]
For photos, provide image classification suggestion
From API that app calls

Could include a 'ID help' function

**Comment by kazlauskis** [comment]
Do you think we should automatically identify new attached photos or should there just be a manual 'ID help' button? In the ButterflyCount we automatically ID pics but if there isn't a network connection at a time then users can also manually trigger the auto-identification later.

**Comment by DavidRoy** [comment]
Just a manual ID help button for this app, thanks

**Comment by JimBacon** [comment]
@kazlauskis, with Biren's help, we now have the the Waarneming API module installed on the live iRecord site. (The Waarneming module is pushed to the modules/custom folder via Git. The API Proxy module which it depends on is added to the upstream repo and ends up in the modules/composer folder.)

You will probably need to edit the allowed CORS origins in https://irecord.org.uk/admin/config/services/api-proxy/settings as I just guessed at `https://irecord-butterflies.app.flumens.io`
