### ISSUE TITLE
Slow performance reported

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#78]
For review at next catch-up...

Device = Ulefone Armor X7 Pro

Reported issue:
1.	The app appears much slower – it takes a while to load the first screen with the pictures of the butterflies on.  These pictures are too big, and so it is often the case that to find the butterfly you are recording means scrolling down two or three screens – and this will be worse once more species are flying.  The older list of butterflies was much more concise.
2. 	I have found on three or four occasions that as I scroll down the list and select the butterfly I am recording, that when I go to the input screen a different species has been selected.  I assume because I am selecting as the screen is scrolling, rather than waiting for the full screen to refresh.  This all takes time.
3.  The screen loading and scrolling is very slow (the previous version was almost instantaneous).  I do not use data on my phone (which is only a year old and usually fast, with no memory issues), so all the information must be being loaded from the app on my phone – it is clearly less well written than the previous version.

**Comment by kazlauskis** [comment]
The main performance difference here is that we show all the species in the same list and in the previous version extra species were hidden under the 'Aditional' button. Also, we use some GPU-expensive blurring effects behind the species cutouts to blend in the photos. We can certainly improve the performance though.

As for the species photo size, yes, we can tweak this and show 3 or more species in a row if that is preferable. Overall, we are showing about the same number of species, but with larger photos, recommended font size labels and the top header visible which allows users to search and navigate back at any point. I understand why people wanted to see everything crammed 7 years ago when the devices were small but now I would suggest keeping the layout more spaced out.

<img width="365" alt="Screenshot 2021-05-18 at 14 39 40" src="https://user-images.githubusercontent.com/7383162/118661456-0a1e0500-b7e7-11eb-9ea7-6c99046b0fbe.png">

<img width="365" alt="Screenshot 2021-05-18 at 14 39 40" src="https://user-images.githubusercontent.com/7383162/118661466-0be7c880-b7e7-11eb-8a52-a92c352f9ed2.png">


<img width="346" alt="Screenshot 2021-05-18 at 14 46 53" src="https://user-images.githubusercontent.com/7383162/118662499-f4f5a600-b7e7-11eb-9015-3314b0a96dd8.png">

**Comment by RichardFoxBC** [comment]
Perhaps we could add a user option in the future (not for version 2) to select how many species to appear on the screen? Personally I think it is fine as it is, and the example Karolis gives above with three columns of species has the problem of species names being split across rows i.e. Small Tortoiseshell, which looks messy

**Comment by DavidRoy** [comment]
discuss at future meeting whether we focus on this for the 2022 version
