### ISSUE TITLE
Suggested change to flow of recording single-sighting

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#79]
Suggestion for review:
1.	When pressing the record button on the main screen, rather than come up with the list of things to update (species, locn, number etc) why not go straight to the species list ?

**Comment by kazlauskis** [comment]
I feel it is almost the same as tapping on the species in the species guide and tapping 'Record', no?

<img width="521" alt="Screenshot 2021-05-18 at 13 53 21" src="https://user-images.githubusercontent.com/7383162/118654380-6af60f00-b7e0-11eb-9072-b18fa0cb3b42.png">

**Comment by DavidRoy** [comment]
Agreed.  Closing this suggestion as it does not reduce taps
