### ISSUE TITLE
Review species images for guide

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#8]
- alternatives for existing photos
- images for all life-cycle stages
- 'confusion species' images

**Comment by DavidRoy** [comment]
Main images = BC species image gallery.  RF/AM to investigate
Life-cycle stages images = complete
Confusion species = DR to obtain from Peter Eeles

**Comment by kazlauskis** [comment]
Just to say that I have shared a OneDrive folder with Richard for adding any gallery photos next to Peter Eeles ones. The photos have now their own sheet in our main excel document.

<img width="306" alt="Screenshot 2021-02-24 at 11 53 24" src="https://user-images.githubusercontent.com/7383162/109127721-a4b9fb00-7746-11eb-935a-712ff7519b47.png">

**Comment by kazlauskis** [comment]
I have all the images now.
