### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#83]
Introduce a basic FAQ page with a small number of issues to start with. In particular, telling people about the List recording option

**Comment by DavidRoy** [comment]
@RichardFoxBC to review help text in the main iRecord app for structure and to identify any text that can be moved across.

Supply any new help text by 5th July to @kazlauskis

**Comment by RichardFoxBC** [comment]
@kazlauskis 
I suggest that this new section sits under Menu, in the Info section, above "Credits".
I suggest we call it Frequently Asked Questions rather than Help.
Use the same approach as in the iRecord app, where there is a short phrase and a plus symbol that can be clicked to reveal more detailed information.

Here is the text I suggest for this first version (comments/edits welcome please @DavidRoy): 

**Where are all my previous records?**
Records that you have submitted from previous versions of the iRecord Butterflies app are all stored safely in the iRecord website. To see these, download them or make changes, visit www.brc.ac.uk/irecord/ and log into your account. Although this app keeps a record of your pending and uploaded sightings, this is not designed to be a permanent repository. The only way to ensure that your records are safe and useful for conservation and research is to upload them.

**Can I record multiple species at a site?**
Yes. Hold down the green 'Record' button for a second or two and an option to start a Species list will appear. This allows you to record multiple species at a site on a particular date.

**Why are species missing from the 'in my area' list?**
The Species section of the app uses existing data from UK butterfly recording and monitoring schemes to present species in the order that they are most likely to be encountered in your general area (the 10km x 10km map square in which you are located) in the current week of the year. Records from the Butterflies for the New Millennium recording scheme for the period 2005-2019 provide the basis for the species known in your area. Other species may be present but not yet recorded in the BNM scheme and therefore will not in 'your area' lists. Submitting records of such species will not alter the ordering of these lists in the short-term but will enable the lists to be refined in future versions of the app.

**Comment by DavidRoy** [comment]
Thanks @RichardFoxBC.  Looks good
