### ISSUE TITLE
Question: is day-flying moth recording possible?

### ISSUE THREAD

**Issue by kitenetter** [NERC-CEH/irecord-butterflies-app#85]
@kazlauskis a user asks how they can record a day-flying moth on the butterflies app, but I don't think this is possible - please can you confirm?

They said:
> Hi, I’m trying to record my sighting of a cinnabar moth today. It is not in your list but your site says I can still record it.

I'm not sure which "site" the user is referring to, will find out.

**Comment by kazlauskis** [comment]
The app doesn't support moths yet #5, whatever this website is, it has incorrect info about the app.

**Comment by DavidRoy** [comment]
I suspect their is confusion between the iRecord butterflies app (butterflies only) and the Big Butterfly Count app (includes some moths).
