### ISSUE TITLE
Missing legend from Dark Green Fritillary / High Brown Fritillary comparison images

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#88]
Hi @kazlauskis, I noticed yesterday (as I happened to be recording these species) that the caption is missing from these images in the app. As with other comparison images, its vital that there is a caption telling the user which species is which. Is this in the spreadsheet or is it one that we missed when originally developing the new app?

**Comment by kazlauskis** [comment]
Yes, it is in the same spreadsheet, **photos** sheet. Let me know when you've added the photo titles and I'll pull it into the app.

**Comment by RichardFoxBC** [comment]
OK @kazlauskis I've added those captions now. Can't understand how I missed them before!
