### ISSUE TITLE
Location of species list moving

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#89]
Hi Karolis, I tested the beta version in the field today and spotted something that doesn't seem right. It probably isn't new but is definitely something that we should check both the logic of our decision making and the implementation.

I created a species list, recorded the location and area size and added some species. I then clicked finish, but then reopened the list as I walked home in case I saw any additional species. I noticed that when I had reached home, the grid reference in the location field was now showing my home location and not the location that I set when I went through the process before starting to record. Surely that isn't right is it? I would expect the location associated with the list to stay static once the user has defined it by clicking on the location button.

Thoughts and comments welcome from everyone!

**Comment by RichardFoxBC** [comment]
Also now when I try to move the location back to where I actually saw the butterflies, the app constantly drags the map back to my current location at home, effectively preventing me from recording the accurate and correct spatial location for the record!

**Comment by kazlauskis** [comment]
@RichardFoxBC I can reproduce this bug. Thanks for reporting I will issue a fix asap.

**Comment by kazlauskis** [comment]
Fixed it now. The bug was introduced in this Beta only and shouldn't affect regular users.

**Comment by RichardFoxBC** [comment]
Many thanks @kazlauskis - interestingly I've just had the same issue reported to me by an app user. Does the beta version get downloaded onto all users' devices (if they have autoupdate on)? If so, that doesn't seem a good idea? Surely testing is better done by a small group so that any bugs don't affect all users.

When will the fixed version be available?

**Comment by kazlauskis** [comment]
Betas only reach the testers - currently you have around 20 on iOS. The fix is already available on iOS and will follow soon on Android.
