### ISSUE TITLE
Provide option to list species alphabetically

### ISSUE THREAD

**Issue by RichardFoxBC** [NERC-CEH/irecord-butterflies-app#90]
After repeated comments from users saying that they would like this feature, we should consider it for a future update. I imagine that it would be a user option in the menu to disable the likelihood lists and just have species ordered alphabetically by vernacular name.

**Comment by kazlauskis** [comment]
It is good to get this validation for the usefulness of the feature from the users. We could either add the sorting options in the Settings or in the main species screen header.
<img width="381" alt="Screenshot 2021-07-19 at 15 14 52" src="https://user-images.githubusercontent.com/7383162/126175039-33890a82-0e4f-404a-9eee-d853dec1290e.png">

**Comment by kazlauskis** [comment]
@RichardFoxBC We are planning to add a sorting toggle setting with 'Alphabetical sorting' label and info text below it: 'By default the species lists are sorted using time and location probability information. You can disable this and sort the species alphabetically.'

This will keep the list filtering as is and will only sort the species alphabetically.  OR do you want to disable any probability filtering altogether and just use the alphabetical sorting of one long list?

**Comment by RichardFoxBC** [comment]
@kazlauskis Thanks for this. I have emailed two beta testers who specifically requested alphabetical species listing to see which option they would prefer. I think I would lean towards the former i.e. alphabetical sorting within the probability-defined subsections. I'll let you know what they say.

**Comment by RichardFoxBC** [comment]
OK all, I've heard back from the two beta testers already. One said they would prefer a single unfiltered list sorted alphabetically, the other that it would be better to keep the probability-filtered sections and sort alphabetically within each one - although they did also have another grumble about the inaccuracy of the probability filtered lists! 

So, as the first step I suggest we give users the option to sort alphabetically within the separate smart species lists. This should work both when the current location is being used as part of the filtering and when it is disabled.

A possible second step for us to consider is whether users should be able to opt out of all probability-based filtering - this would enable them to see a single long list of all the species in the app. If we do think this is OK, would it be possible as part of the version 3 work or would it have to wait for a later update?

**Comment by kazlauskis** [comment]
Thanks, lets sort with the filtering for now and create another ticket for disabling the filters altogether.
