### ISSUE TITLE
Add location name suggestions (geocoding)

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/irecord-butterflies-app#92]
At the moment, the app suggest location names using your previously recorded locations. It would be good to suggest the names (geocode) and zoom into that location on the map. This probably wouldn't auto select this location, just zoom in. 

Example, see FIT Count app location page.

**Comment by DavidRoy** [comment]
Will not take this forward as we rely on the phone GPS.  Richard to write an FAQ that the phone to be used in the field and BNM is an alternative
