### ISSUE TITLE
Users unable to upload records when account not activated

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#93]
Getting several reports of this.  Users register but don't complete the email activation.  They attempt to upload records but nothing happens.

Solutions = warning message to users that their account is not activated.  Option to request new activation link via email

**Comment by kazlauskis** [comment]
There are multiple ways to solve this but the best one would be to use a modern authentication that is provided by the Drupal 8+. Second best alternative would be to improve the current Drupal Indicia API module and update the app with that.
