### ISSUE TITLE
review location funcationality

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#94]
Reports of records associated with home address.  Suggestion from the verifier:

“the app ought to be able to catch this - a change of location with no significant change of grid reference should be automatically queried by the app before submission.”  It’s also been suggested that “a note to the user that the gridref will be derived from their current location might also help… The reverse situation occurred with a few records too. The gridref changed significantly because they went to another site, but they failed to change the location description. This again could be automatically queried by the app – this situation arose with the iRecord App, but maybe iRecord Butterflies would similarly fail?”

**Comment by kazlauskis** [comment]
In the iRecord App we allow to lock a location name so I can easily imagine this could have been forgotten and multiple records submitted using an old name - if that is an issue we should probably open a ticket for the iRecord App then too.

As for the location setting in this app, this applies only to the Species List survey and we could indeed add something like the verifier suggests where we could warn the user if a new species in the list is a long distance away from the previous species in the list or from the top survey location.

**Comment by DavidRoy** [comment]
Close as suspect an old issue that has been resolved
