### ISSUE TITLE
Addition to FAQ

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/irecord-butterflies-app#95]
+ How to edit your sightings after they are uploaded
Once records are uploaded from the app, they can no longer be edited from within the app, and instead you need to do the following :
1.	Go to the iRecord website (www.brc.ac.uk/irecord) and log in (using the same username and password as you have used to register on the app)
2.	Go to the Explore - My records page (https://www.brc.ac.uk/irecord/my-records) and find the record that needs to be edited
3.	Click on the edit button (on the right-hand side of the page, pencil and pad icon)
4.	Make the required edits and then click on Submit to save

**Comment by DavidRoy** [comment]
Richard to edit and confirm text

**Comment by RichardFoxBC** [comment]
Text looks good to me. Over to you @kazlauskis to implement this new FAQ please
