### ISSUE TITLE
Improve location name field search

### ISSUE THREAD

**Issue by Vilius-Stankaitis** [NERC-CEH/irecord-butterflies-app#99]
Feature request: https://www.brc.ac.uk/irecord/node/8438

**Comment by DavidRoy** [comment]
Options discussed
- locking (not favoured)
- add a button to select 'use previous site name'
- improve ordering of previous site names
- add in iRecord 'favourites' functionality

Favour improved sorting.  Prioritize where site names match the start of string text or a word within the site name
